services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 55679:55679 # zpages extension

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [otel-collector]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_UID=turborepo-runs
    ports:
      - "3001:3000"
    depends_on: [prometheus]

  nats:
    image: "nats:latest"
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port
    command: -js # Enable JetStream for NATS persistence
    volumes:
      - nats_data:/data # Volume for NATS JetStream data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Redis default port
    volumes:
      - redis_data:/data # Volume for Redis persistence
    command: redis-server --appendonly yes # Enable AOF persistence for Redis

  questdb:
    image: "questdb/questdb:latest"
    hostname: questdb
    ports:
      - "9000:9000" # Web Console, REST API, Prometheus
      - "9009:9009" # InfluxDB Line Protocol
      - "8812:8812" # PostgreSQL Wire Protocol
      - "9003:9003" # HTTP MinIO client
    volumes:
      - questdb_data:/data

volumes:
  nats_data:
  redis_data:
  questdb_data:
  prometheus-data:
  grafana-storage:
