// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client/index.js";
import type {
  AccountTemplateGetUserTemplatesData,
  AccountTemplateGetUserTemplatesResponses,
  AccountTemplateRuleGetAllAttachedRulesData,
  AccountTemplateRuleGetAllAttachedRulesResponses,
  AutoOcoBracketsDeleteData,
  AutoOcoBracketsDeleteResponses,
  AutoOcoBracketsGetData,
  AutoOcoBracketsGetResponses,
  AutoOcoBracketsPostData,
  AutoOcoBracketsPostResponses,
  ChartDataDeleteData,
  ChartDataDeleteResponses,
  ChartDataGetData,
  ChartDataGetResponses,
  ChartDataPostData,
  ChartDataPostResponses,
  ChartsGetAllData,
  ChartsGetAllResponses,
  ChartsGetChartData,
  ChartsGetChartResponses,
  ChartsRemoveData,
  ChartsRemoveResponses,
  ChartsSaveChartData,
  ChartsSaveChartResponses,
  ChartTemplatesGetAllData,
  ChartTemplatesGetAllResponses,
  ChartTemplatesGetChartTemplateData,
  ChartTemplatesGetChartTemplateResponses,
  ChartTemplatesRemoveData,
  ChartTemplatesRemoveResponses,
  ChartTemplatesSaveChartTemplateData,
  ChartTemplatesSaveChartTemplateResponses,
  ContractLimitGetAllData,
  ContractLimitGetAllResponses,
  ContractLimitSetData,
  ContractLimitSetResponses,
  DrawingTemplatesGetAllData,
  DrawingTemplatesGetAllNamesData,
  DrawingTemplatesGetAllNamesResponses,
  DrawingTemplatesGetAllResponses,
  DrawingTemplatesGetDrawingTemplateData,
  DrawingTemplatesGetDrawingTemplateDepracatedData,
  DrawingTemplatesGetDrawingTemplateDepracatedResponses,
  DrawingTemplatesGetDrawingTemplateResponses,
  DrawingTemplatesRemoveData,
  DrawingTemplatesRemoveDrawingTemplateData,
  DrawingTemplatesRemoveDrawingTemplateResponses,
  DrawingTemplatesRemoveResponses,
  DrawingTemplatesSaveDrawingTemplateData,
  DrawingTemplatesSaveDrawingTemplateDepracatedData,
  DrawingTemplatesSaveDrawingTemplateDepracatedResponses,
  DrawingTemplatesSaveDrawingTemplateResponses,
  ForgotPasswordGetData,
  ForgotPasswordGetResponses,
  ForgotPasswordPostData,
  ForgotPasswordPostResponses,
  JournalLogDeleteData,
  JournalLogDeleteResponses,
  JournalLogGetForDayData,
  JournalLogGetForDayResponses,
  JournalLogGetForRangeData,
  JournalLogGetForRangeResponses,
  JournalLogGetForTradeData,
  JournalLogGetForTradeResponses,
  JournalLogUpsertData,
  JournalLogUpsertResponses,
  LayoutsDeleteData,
  LayoutsDeleteResponses,
  LayoutsGetData,
  LayoutsGetResponses,
  LayoutsPostData,
  LayoutsPostResponses,
  LineToolsLoadData,
  LineToolsLoadResponses,
  LineToolsRemoveData,
  LineToolsRemoveResponses,
  LineToolsSaveLineToolData,
  LineToolsSaveLineToolResponses,
  LinkedOrderGetLinkedOrdersData,
  LinkedOrderGetLinkedOrdersResponses,
  LinkedOrderLinkOrdersData,
  LinkedOrderLinkOrdersResponses,
  LinkedOrderUnlinkOrdersData,
  LinkedOrderUnlinkOrdersResponses,
  LoginApiLoginData,
  LoginApiLoginResponses,
  LoginLoginData,
  LoginLoginResponses,
  LoginLoginV2Data,
  LoginLoginV2Responses,
  MarketClosureGetData,
  MarketClosureGetResponses,
  MarketStatusDebugMarketStatusData,
  MarketStatusDebugMarketStatusResponses,
  MarketStatusGetData,
  MarketStatusGetMarketsData,
  MarketStatusGetMarketsResponses,
  MarketStatusGetResponses,
  MarketStatusGetSummaryData,
  MarketStatusGetSummaryResponses,
  MarketStatusResetAllMarketStatusData,
  MarketStatusResetAllMarketStatusResponses,
  MarketStatusResetMarketStatusData,
  MarketStatusResetMarketStatusResponses,
  MarketStatusSetAllMarketStatusData,
  MarketStatusSetAllMarketStatusResponses,
  MarketStatusSetMarketStatusData,
  MarketStatusSetMarketStatusResponses,
  MetadataGetData,
  MetadataGetResponses,
  MigrateDataMigrateChartsData,
  MigrateDataMigrateChartsPartialData,
  MigrateDataMigrateChartsPartialResponses,
  MigrateDataMigrateChartsResponses,
  MultiFactorAuthenticationAdminDisable2FaData,
  MultiFactorAuthenticationAdminDisable2FaResponses,
  MultiFactorAuthenticationCreateData,
  MultiFactorAuthenticationCreateResponses,
  MultiFactorAuthenticationCreateV2Data,
  MultiFactorAuthenticationCreateV2Responses,
  MultiFactorAuthenticationDisable2FaData,
  MultiFactorAuthenticationDisable2FaResponses,
  MultiFactorAuthenticationDisableMfaData,
  MultiFactorAuthenticationDisableMfaResponses,
  MultiFactorAuthenticationHas2FaData,
  MultiFactorAuthenticationHas2FaResponses,
  MultiFactorAuthenticationHasMfaData,
  MultiFactorAuthenticationHasMfaResponses,
  MultiFactorAuthenticationRegenerateRecoveryCodesData,
  MultiFactorAuthenticationRegenerateRecoveryCodesResponses,
  MultiFactorAuthenticationRequestEmailCodeData,
  MultiFactorAuthenticationRequestEmailCodeResponses,
  MultiFactorAuthenticationSubmit2FaData,
  MultiFactorAuthenticationSubmit2FaResponses,
  MultiFactorAuthenticationSubmitMfaData,
  MultiFactorAuthenticationSubmitMfaResponses,
  MultiFactorAuthenticationSubmitRecoveryCodeData,
  MultiFactorAuthenticationSubmitRecoveryCodeResponses,
  OnboardingCreateSubscriptionData,
  OnboardingCreateSubscriptionResponses,
  OnboardingGetOnboardingDataData,
  OnboardingGetOnboardingDataResponses,
  OnboardingRequestEmailAuthCodeData,
  OnboardingRequestEmailAuthCodeResponses,
  OnboardingSetPasswordData,
  OnboardingSetPasswordResponses,
  OnboardingSetupMfaData,
  OnboardingSetupMfaResponses,
  OnboardingSignAgreementsData,
  OnboardingSignAgreementsResponses,
  OrderCancelAccountOrderByContractIdData,
  OrderCancelAccountOrderByContractIdResponses,
  OrderCancelAccountOrderByIdData,
  OrderCancelAccountOrderByIdResponses,
  OrderCancelAccountOrderBySymbolIdData,
  OrderCancelAccountOrderBySymbolIdResponses,
  OrderCancelAllAccountOrdersData,
  OrderCancelAllAccountOrdersResponses,
  OrderEditOrderData,
  OrderEditOrderResponses,
  OrderGetData,
  OrderGetResponses,
  OrderPostData,
  OrderPostResponses,
  OrderPostWithContractData,
  OrderPostWithContractResponses,
  OrderPutTrailingOrderDistanceData,
  OrderPutTrailingOrderDistanceResponses,
  OrderUpdateStopLossAccountData,
  OrderUpdateStopLossAccountResponses,
  OrderUpdateStopLossData,
  OrderUpdateStopLossResponses,
  OrderUserExportCsvData,
  OrderUserExportCsvResponses,
  OrderUserExportJsonData,
  OrderUserExportJsonResponses,
  PersonalLockoutAddData,
  PersonalLockoutAddResponses,
  PersonalLockoutGetActiveData,
  PersonalLockoutGetActiveResponses,
  PersonalLockoutGetAllData,
  PersonalLockoutGetAllResponses,
  PositionCloseAllData,
  PositionCloseAllResponses,
  PositionCloseByContractData,
  PositionCloseByContractResponses,
  PositionCloseData,
  PositionCloseResponses,
  PositionGetAllByUserData,
  PositionGetAllByUserResponses,
  PositionGetByTradingAccountData,
  PositionGetByTradingAccountResponses,
  PositionGetData,
  PositionGetResponses,
  PositionPutRiskToMakeData,
  PositionPutRiskToMakeResponses,
  PositionPutSltpData,
  PositionPutSltpResponses,
  PositionReverseByContractData,
  PositionReverseByContractResponses,
  PositionReverseByContractWithTimeTypeData,
  PositionReverseByContractWithTimeTypeResponses,
  PositionReverseData,
  PositionReverseResponses,
  PositionReverseWithTimeTypeData,
  PositionReverseWithTimeTypeResponses,
  RegisterRegisterData,
  RegisterRegisterResponses,
  RiskSettingsLockoutAddData,
  RiskSettingsLockoutAddForDayData,
  RiskSettingsLockoutAddForDayResponses,
  RiskSettingsLockoutAddResponses,
  RiskSettingsLockoutGetData,
  RiskSettingsLockoutGetResponses,
  SessionValidateData,
  SessionValidateResponses,
  SingleSignOnGenerateData,
  SingleSignOnGenerateResponses,
  SingleSignOnLoginData,
  SingleSignOnLoginResponses,
  StatisticsCheckAccountSharingData,
  StatisticsCheckAccountSharingResponses,
  StatisticsGetAccountNameData,
  StatisticsGetAccountNameResponses,
  StatisticsGetDailyData,
  StatisticsGetDailyResponses,
  StatisticsGetDayStatsData,
  StatisticsGetDayStatsResponses,
  StatisticsGetLifetimeStatsData,
  StatisticsGetLifetimeStatsResponses,
  StatisticsGetMonthlyData,
  StatisticsGetMonthlyResponses,
  StatisticsGetProfitFactorData,
  StatisticsGetProfitFactorResponses,
  StatisticsGetTodayStatsData,
  StatisticsGetTodayStatsResponses,
  StatisticsGetTradesForDayData,
  StatisticsGetTradesForDayResponses,
  StatisticsGetTradesForRangeData,
  StatisticsGetTradesForRangeResponses,
  StatisticsGetWeeklyData,
  StatisticsGetWeeklyResponses,
  StatisticsGetWinLossAvgData,
  StatisticsGetWinLossAvgResponses,
  StatisticsSetAccountSharingData,
  StatisticsSetAccountSharingResponses,
  StudyTemplatesGetAllData,
  StudyTemplatesGetAllResponses,
  StudyTemplatesGetStudyTemplateData,
  StudyTemplatesGetStudyTemplateResponses,
  StudyTemplatesRemoveByNameData,
  StudyTemplatesRemoveByNameResponses,
  StudyTemplatesSaveStudyTemplateData,
  StudyTemplatesSaveStudyTemplateResponses,
  SymbolBlockAddData,
  SymbolBlockAddResponses,
  SymbolBlockGetAllData,
  SymbolBlockGetAllResponses,
  SymbolBlockRemoveData,
  SymbolBlockRemoveResponses,
  SymbolBlockSetData,
  SymbolBlockSetResponses,
  TiltActivateData,
  TiltActivateResponses,
  TiltActivateWithAccountIdData,
  TiltActivateWithAccountIdResponses,
  TradeClockSetTradeClockData,
  TradeClockSetTradeClockResponses,
  TradeGetData,
  TradeGetInRangeData,
  TradeGetInRangeResponses,
  TradeGetResponses,
  TradeLimitAddTradeLimitsData,
  TradeLimitAddTradeLimitsResponses,
  TradeUserExportCsvData,
  TradeUserExportCsvResponses,
  TradeUserExportJsonData,
  TradeUserExportJsonResponses,
  TradingAccountClearFollowersData,
  TradingAccountClearFollowersResponses,
  TradingAccountFollowData,
  TradingAccountFollowResponses,
  TradingAccountGetData,
  TradingAccountGetFollowEntriesData,
  TradingAccountGetFollowEntriesResponses,
  TradingAccountGetResponses,
  TradingAccountSetAccountNicknameData,
  TradingAccountSetAccountNicknameResponses,
  TradingAccountSetAutoOcoBracketsData,
  TradingAccountSetAutoOcoBracketsResponses,
  TradingAccountSetPersonalDailyLimitsData,
  TradingAccountSetPersonalDailyLimitsResponses,
  TradingAccountSetPersonalDailyLossLimitData,
  TradingAccountSetPersonalDailyLossLimitResponses,
  TradingAccountSetPositionBracketsData,
  TradingAccountSetPositionBracketsResponses,
  TradingAccountStateLogGetTradingAccountStateLogData,
  TradingAccountStateLogGetTradingAccountStateLogResponses,
  TradingAccountStopTradingData,
  TradingAccountStopTradingResponses,
  TradingAccountUnfollowData,
  TradingAccountUnfollowResponses,
  TradingRuleGetTradingRulesData,
  TradingRuleGetTradingRulesResponses,
  UserAgreementGetData,
  UserAgreementGetRequiredData,
  UserAgreementGetRequiredResponses,
  UserAgreementGetResponses,
  UserAgreementLegacyGetRequiredData,
  UserAgreementLegacyGetRequiredResponses,
  UserAgreementSignData,
  UserAgreementSignResponses,
  UserContractGetAllData,
  UserContractGetAllResponses,
  UserContractGetNonProfessionalData,
  UserContractGetNonProfessionalResponses,
  UserContractGetProfessionalData,
  UserContractGetProfessionalResponses,
  UserCreateApiKeyData,
  UserCreateApiKeyResponses,
  UserDataUploadUploadUserDataData,
  UserDataUploadUploadUserDataResponses,
  UserGetApiKeysData,
  UserGetApiKeysResponses,
  UserGetCurrentTimeUtcData,
  UserGetCurrentTimeUtcResponses,
  UserGetDashboardLinkUrlData,
  UserGetDashboardLinkUrlResponses,
  UserGetData,
  UserGetIntercomHashData,
  UserGetIntercomHashResponses,
  UserGetResponses,
  UserNotificationGetUnreadNotificationsData,
  UserNotificationGetUnreadNotificationsResponses,
  UserNotificationReadNotificationData,
  UserNotificationReadNotificationResponses,
  UserPutAgreementsCompletedData,
  UserPutAgreementsCompletedResponses,
  UserRevokeApiKeyData,
  UserRevokeApiKeyResponses,
  UserRoleGetAvailableRolesData,
  UserRoleGetAvailableRolesResponses,
  UserRoleGetRolesByUserIdData,
  UserRoleGetRolesByUserIdResponses,
  UserRoleGetUserRolesByUserIdData,
  UserRoleGetUserRolesByUserIdResponses,
  UserRoleHasUserRoleData,
  UserRoleHasUserRoleResponses,
  UserSettingsGetData,
  UserSettingsGetResponses,
  UserSettingsPostData,
  UserSettingsPostResponses,
  UserSettingsPostV2Data,
  UserSettingsPostV2Responses,
  ViolationsGetActiveViolationData,
  ViolationsGetActiveViolationResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Retrieves a list of all templates associated with a specific user
 */
export const accountTemplateGetUserTemplates = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AccountTemplateGetUserTemplatesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AccountTemplateGetUserTemplatesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/AccountTemplate/userTemplates",
    ...options,
  });
};

/**
 * Retrieves a list of all rule configurations for the specified account template id
 */
export const accountTemplateRuleGetAllAttachedRules = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AccountTemplateRuleGetAllAttachedRulesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    AccountTemplateRuleGetAllAttachedRulesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/AccountTemplateRule/rules/{accountTemplateId}/all",
    ...options,
  });
};

export const autoOcoBracketsDelete = <ThrowOnError extends boolean = false>(
  options: Options<AutoOcoBracketsDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    AutoOcoBracketsDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: "/brackets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const autoOcoBracketsGet = <ThrowOnError extends boolean = false>(
  options?: Options<AutoOcoBracketsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AutoOcoBracketsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/brackets",
    ...options,
  });
};

export const autoOcoBracketsPost = <ThrowOnError extends boolean = false>(
  options: Options<AutoOcoBracketsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AutoOcoBracketsPostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/brackets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const chartDataDelete = <ThrowOnError extends boolean = false>(
  options?: Options<ChartDataDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ChartDataDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts_old/1.1/charts",
    ...options,
  });
};

export const chartDataGet = <ThrowOnError extends boolean = false>(
  options?: Options<ChartDataGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ChartDataGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts_old/1.1/charts",
    ...options,
  });
};

export const chartDataPost = <ThrowOnError extends boolean = false>(
  options?: Options<ChartDataPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ChartDataPostResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/charts_old/1.1/charts",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
  });
};

export const chartsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ChartsGetAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ChartsGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts/all",
    ...options,
  });
};

export const chartsRemove = <ThrowOnError extends boolean = false>(
  options: Options<ChartsRemoveData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ChartsRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts/remove/{id}",
    ...options,
  });
};

export const chartsSaveChart = <ThrowOnError extends boolean = false>(
  options: Options<ChartsSaveChartData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChartsSaveChartResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const chartsGetChart = <ThrowOnError extends boolean = false>(
  options: Options<ChartsGetChartData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ChartsGetChartResponses,
    unknown,
    ThrowOnError
  >({
    url: "/charts/content/{chartId}",
    ...options,
  });
};

export const chartTemplatesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ChartTemplatesGetAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ChartTemplatesGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chart-templates/all",
    ...options,
  });
};

export const chartTemplatesRemove = <ThrowOnError extends boolean = false>(
  options: Options<ChartTemplatesRemoveData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ChartTemplatesRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chart-templates/remove/{templateName}",
    ...options,
  });
};

export const chartTemplatesSaveChartTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChartTemplatesSaveChartTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChartTemplatesSaveChartTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chart-templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const chartTemplatesGetChartTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChartTemplatesGetChartTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ChartTemplatesGetChartTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chart-templates/content/{templateName}",
    ...options,
  });
};

export const contractLimitGetAll = <ThrowOnError extends boolean = false>(
  options: Options<ContractLimitGetAllData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContractLimitGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ContractLimit/all/{accountId}",
    ...options,
  });
};

export const contractLimitSet = <ThrowOnError extends boolean = false>(
  options: Options<ContractLimitSetData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContractLimitSetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ContractLimit/set",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const drawingTemplatesGetAll = <ThrowOnError extends boolean = false>(
  options: Options<DrawingTemplatesGetAllData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    DrawingTemplatesGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/all/{toolName}",
    ...options,
  });
};

export const drawingTemplatesGetAllNames = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DrawingTemplatesGetAllNamesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    DrawingTemplatesGetAllNamesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/all/{toolName}/names",
    ...options,
  });
};

export const drawingTemplatesRemoveDrawingTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DrawingTemplatesRemoveDrawingTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DrawingTemplatesRemoveDrawingTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const drawingTemplatesSaveDrawingTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DrawingTemplatesSaveDrawingTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DrawingTemplatesSaveDrawingTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/save",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const drawingTemplatesGetDrawingTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DrawingTemplatesGetDrawingTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DrawingTemplatesGetDrawingTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/content",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const drawingTemplatesGetDrawingTemplateDepracated = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DrawingTemplatesGetDrawingTemplateDepracatedData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    DrawingTemplatesGetDrawingTemplateDepracatedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/content/{toolName}/{templateName}",
    ...options,
  });
};

/**
 * @deprecated
 */
export const drawingTemplatesSaveDrawingTemplateDepracated = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DrawingTemplatesSaveDrawingTemplateDepracatedData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    DrawingTemplatesSaveDrawingTemplateDepracatedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const drawingTemplatesRemove = <ThrowOnError extends boolean = false>(
  options: Options<DrawingTemplatesRemoveData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    DrawingTemplatesRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/drawing-templates/remove/{toolName}/{templateName}",
    ...options,
  });
};

/**
 * Begin the password reset process for a user.
 * This will send out a password reset email to the user.
 */
export const forgotPasswordGet = <ThrowOnError extends boolean = false>(
  options?: Options<ForgotPasswordGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ForgotPasswordGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ForgotPassword",
    ...options,
  });
};

/**
 * Complete the password reset process for a user.
 */
export const forgotPasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ForgotPasswordPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ForgotPasswordPostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ForgotPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const journalLogUpsert = <ThrowOnError extends boolean = false>(
  options: Options<JournalLogUpsertData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    JournalLogUpsertResponses,
    unknown,
    ThrowOnError
  >({
    url: "/JournalLog/upsert",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const journalLogGetForDay = <ThrowOnError extends boolean = false>(
  options: Options<JournalLogGetForDayData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    JournalLogGetForDayResponses,
    unknown,
    ThrowOnError
  >({
    url: "/JournalLog/getForDay",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const journalLogGetForTrade = <ThrowOnError extends boolean = false>(
  options: Options<JournalLogGetForTradeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    JournalLogGetForTradeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/JournalLog/getForTrade",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const journalLogGetForRange = <ThrowOnError extends boolean = false>(
  options: Options<JournalLogGetForRangeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    JournalLogGetForRangeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/JournalLog/getForRange",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const journalLogDelete = <ThrowOnError extends boolean = false>(
  options: Options<JournalLogDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    JournalLogDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: "/JournalLog/delete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const layoutsDelete = <ThrowOnError extends boolean = false>(
  options?: Options<LayoutsDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    LayoutsDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Layouts",
    ...options,
  });
};

export const layoutsGet = <ThrowOnError extends boolean = false>(
  options?: Options<LayoutsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LayoutsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Layouts",
    ...options,
  });
};

export const layoutsPost = <ThrowOnError extends boolean = false>(
  options: Options<LayoutsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LayoutsPostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Layouts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const lineToolsLoad = <ThrowOnError extends boolean = false>(
  options: Options<LineToolsLoadData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    LineToolsLoadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/line-tools/load/{layoutId}/{chartId}",
    ...options,
  });
};

export const lineToolsRemove = <ThrowOnError extends boolean = false>(
  options: Options<LineToolsRemoveData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    LineToolsRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/line-tools/remove/{id}",
    ...options,
  });
};

export const lineToolsSaveLineTool = <ThrowOnError extends boolean = false>(
  options: Options<LineToolsSaveLineToolData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LineToolsSaveLineToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/line-tools",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const linkedOrderUnlinkOrders = <ThrowOnError extends boolean = false>(
  options: Options<LinkedOrderUnlinkOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    LinkedOrderUnlinkOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/LinkedOrder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const linkedOrderGetLinkedOrders = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LinkedOrderGetLinkedOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LinkedOrderGetLinkedOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/LinkedOrder",
    ...options,
  });
};

/**
 * @deprecated
 */
export const linkedOrderLinkOrders = <ThrowOnError extends boolean = false>(
  options: Options<LinkedOrderLinkOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LinkedOrderLinkOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/LinkedOrder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Authenticates a user based on the provided login request.
 */
export const loginLogin = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginLoginResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Authenticates a user based on the provided login request.
 */
export const loginLoginV2 = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginV2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginLoginV2Responses,
    unknown,
    ThrowOnError
  >({
    url: "/Login/v2",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const loginApiLogin = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginApiLoginResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Login/key",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const marketClosureGet = <ThrowOnError extends boolean = false>(
  options?: Options<MarketClosureGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketClosureGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketClosure",
    ...options,
  });
};

/**
 * @deprecated
 */
export const marketStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<MarketStatusGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketStatusGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus",
    ...options,
  });
};

export const marketStatusGetSummary = <ThrowOnError extends boolean = false>(
  options?: Options<MarketStatusGetSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketStatusGetSummaryResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/summary",
    ...options,
  });
};

export const marketStatusGetMarkets = <ThrowOnError extends boolean = false>(
  options?: Options<MarketStatusGetMarketsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MarketStatusGetMarketsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/markets",
    ...options,
  });
};

export const marketStatusSetMarketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MarketStatusSetMarketStatusData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MarketStatusSetMarketStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/setStatus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const marketStatusSetAllMarketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MarketStatusSetAllMarketStatusData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MarketStatusSetAllMarketStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/setStatus/all",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const marketStatusResetMarketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MarketStatusResetMarketStatusData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MarketStatusResetMarketStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/resetStatus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const marketStatusResetAllMarketStatus = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MarketStatusResetAllMarketStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    MarketStatusResetAllMarketStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/resetStatus/all",
    ...options,
  });
};

export const marketStatusDebugMarketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MarketStatusDebugMarketStatusData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MarketStatusDebugMarketStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MarketStatus/debug/{symbolId}/{num}",
    ...options,
  });
};

export const metadataGet = <ThrowOnError extends boolean = false>(
  options?: Options<MetadataGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MetadataGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Metadata",
    ...options,
  });
};

export const migrateDataMigrateChartsPartial = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MigrateDataMigrateChartsPartialData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MigrateDataMigrateChartsPartialResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MigrateData/partialcharts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const migrateDataMigrateCharts = <ThrowOnError extends boolean = false>(
  options: Options<MigrateDataMigrateChartsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    MigrateDataMigrateChartsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MigrateData/charts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const multiFactorAuthenticationCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationCreateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationCreateV2 = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationCreateV2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationCreateV2Responses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/v2/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const multiFactorAuthenticationSubmit2Fa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationSubmit2FaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationSubmit2FaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/submit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationSubmitMfa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationSubmitMfaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationSubmitMfaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/v2/submit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationSubmitRecoveryCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MultiFactorAuthenticationSubmitRecoveryCodeData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationSubmitRecoveryCodeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/submitRecovery",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationRegenerateRecoveryCodes = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    MultiFactorAuthenticationRegenerateRecoveryCodesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    MultiFactorAuthenticationRegenerateRecoveryCodesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/regenerateRecoveryCodes",
    ...options,
  });
};

export const multiFactorAuthenticationHas2Fa = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MultiFactorAuthenticationHas2FaData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MultiFactorAuthenticationHas2FaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/has2FA",
    ...options,
  });
};

/**
 * @deprecated
 */
export const multiFactorAuthenticationDisable2Fa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationDisable2FaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationDisable2FaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/Disable2FA",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationDisableMfa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationDisableMfaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationDisableMfaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/v2/DisableMfa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationAdminDisable2Fa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationAdminDisable2FaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationAdminDisable2FaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/AdminDisable2FA",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationRequestEmailCode = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationRequestEmailCodeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationRequestEmailCodeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/requestEmailCode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const multiFactorAuthenticationHasMfa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MultiFactorAuthenticationHasMfaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    MultiFactorAuthenticationHasMfaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/MultiFactorAuthentication/hasMfa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get onboarding data including user info, current step, required agreements, and available subscriptions.
 */
export const onboardingGetOnboardingData = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OnboardingGetOnboardingDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OnboardingGetOnboardingDataResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/data",
    ...options,
  });
};

/**
 * Request an email authentication code for the user.
 * This will send the user an email with the authentication code.
 */
export const onboardingRequestEmailAuthCode = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OnboardingRequestEmailAuthCodeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OnboardingRequestEmailAuthCodeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/requestEmailAuthCode",
    ...options,
  });
};

/**
 * Step 1: Set the user's password.
 */
export const onboardingSetPassword = <ThrowOnError extends boolean = false>(
  options: Options<OnboardingSetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OnboardingSetPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Step 2: Configure Multi-Factor Authentication (MFA) using an authenticator app.
 */
export const onboardingSetupMfa = <ThrowOnError extends boolean = false>(
  options: Options<OnboardingSetupMfaData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OnboardingSetupMfaResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/mfa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Step 3: Create the user's subscription.
 */
export const onboardingCreateSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OnboardingCreateSubscriptionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OnboardingCreateSubscriptionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/subscription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Step 4: Sign all required user agreements and finalize onboarding.
 */
export const onboardingSignAgreements = <ThrowOnError extends boolean = false>(
  options: Options<OnboardingSignAgreementsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OnboardingSignAgreementsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Onboarding/agreements",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Cancels all open orders for an account.
 */
export const orderCancelAllAccountOrders = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderCancelAllAccountOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    OrderCancelAllAccountOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/cancel/{accountId}/all",
    ...options,
  });
};

/**
 * Cancels all open orders on a symbol for an account.
 */
export const orderCancelAccountOrderBySymbolId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderCancelAccountOrderBySymbolIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    OrderCancelAccountOrderBySymbolIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/cancel/{accountId}/symbol/{symbolId}",
    ...options,
  });
};

/**
 * Cancels all open orders on a contract for an account.
 */
export const orderCancelAccountOrderByContractId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderCancelAccountOrderByContractIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    OrderCancelAccountOrderByContractIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/cancel/{accountId}/contract/{contractId}",
    ...options,
  });
};

/**
 * Updates the trailing distance of an existing order.
 */
export const orderPutTrailingOrderDistance = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderPutTrailingOrderDistanceData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    OrderPutTrailingOrderDistanceResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/edit/trailingDistance/{orderId}",
    ...options,
  });
};

/**
 * Updates the limit price of an existing order.
 */
export const orderEditOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderEditOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    OrderEditOrderResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/edit/stopLimit/{orderId}",
    ...options,
  });
};

/**
 * Cancels an order for an account.
 */
export const orderCancelAccountOrderById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderCancelAccountOrderByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    OrderCancelAccountOrderByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/cancel/{accountId}/id/{orderId}",
    ...options,
  });
};

/**
 * Retrieves a list of recent orders for an account.
 *
 * Recent orders are defined as orders that were created within the last 24 hours.
 */
export const orderGet = <ThrowOnError extends boolean = false>(
  options?: Options<OrderGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrderGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order",
    ...options,
  });
};

/**
 * Places an order.
 *
 * This method supports both live and simulated trading accounts.
 * If the account is a follower account, the order placement is rejected.
 */
export const orderPost = <ThrowOnError extends boolean = false>(
  options: Options<OrderPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderPostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const orderUserExportJson = <ThrowOnError extends boolean = false>(
  options: Options<OrderUserExportJsonData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderUserExportJsonResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/user/export/json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const orderUserExportCsv = <ThrowOnError extends boolean = false>(
  options: Options<OrderUserExportCsvData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderUserExportCsvResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/user/export/csv",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const orderUpdateStopLossAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OrderUpdateStopLossAccountData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderUpdateStopLossAccountResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/editStopLossAccount",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * @deprecated
 */
export const orderUpdateStopLoss = <ThrowOnError extends boolean = false>(
  options: Options<OrderUpdateStopLossData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderUpdateStopLossResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/editStopLoss",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Places an order.
 *
 * This method supports both live and simulated trading accounts.
 * If the account is a follower account, the order placement is rejected.
 */
export const orderPostWithContract = <ThrowOnError extends boolean = false>(
  options: Options<OrderPostWithContractData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderPostWithContractResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Order/postWithContract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const personalLockoutGetActive = <ThrowOnError extends boolean = false>(
  options: Options<PersonalLockoutGetActiveData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    PersonalLockoutGetActiveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/PersonalLockout/active/{tradingAccountId}",
    ...options,
  });
};

export const personalLockoutGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<PersonalLockoutGetAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PersonalLockoutGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/PersonalLockout/all",
    ...options,
  });
};

export const personalLockoutAdd = <ThrowOnError extends boolean = false>(
  options: Options<PersonalLockoutAddData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PersonalLockoutAddResponses,
    unknown,
    ThrowOnError
  >({
    url: "/PersonalLockout/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Closes an open position on the symbol for an account.
 */
export const positionClose = <ThrowOnError extends boolean = false>(
  options: Options<PositionCloseData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    PositionCloseResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/close/{accountId}/symbol/{symbolId}",
    ...options,
  });
};

/**
 * Closes an open position on the contract for an account.
 */
export const positionCloseByContract = <ThrowOnError extends boolean = false>(
  options: Options<PositionCloseByContractData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    PositionCloseByContractResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/close/{accountId}/contract/{contractId}",
    ...options,
  });
};

/**
 * Closes all open positions for an account.
 */
export const positionCloseAll = <ThrowOnError extends boolean = false>(
  options: Options<PositionCloseAllData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    PositionCloseAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/close/{accountId}",
    ...options,
  });
};

/**
 * Updates the to-risk and to-make targets for a position.
 */
export const positionPutRiskToMake = <ThrowOnError extends boolean = false>(
  options?: Options<PositionPutRiskToMakeData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PositionPutRiskToMakeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/riskToMake",
    ...options,
  });
};

/**
 * Updates the stop-loss and take-profit values for a position.
 */
export const positionPutSltp = <ThrowOnError extends boolean = false>(
  options?: Options<PositionPutSltpData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    PositionPutSltpResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/sltp",
    ...options,
  });
};

/**
 * Reverses a position on a symbol for an account.
 */
export const positionReverse = <ThrowOnError extends boolean = false>(
  options?: Options<PositionReverseData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionReverseResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/reverse",
    ...options,
  });
};

/**
 * Reverses a position on a symbol for an account.
 */
export const positionReverseWithTimeType = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PositionReverseWithTimeTypeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionReverseWithTimeTypeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/reverseWithTimeType",
    ...options,
  });
};

export const positionReverseByContract = <ThrowOnError extends boolean = false>(
  options?: Options<PositionReverseByContractData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionReverseByContractResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/reverseByContract",
    ...options,
  });
};

/**
 * Reverses a position on a contract for an account.
 */
export const positionReverseByContractWithTimeType = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PositionReverseByContractWithTimeTypeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionReverseByContractWithTimeTypeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/reverseByContractWithTimeType",
    ...options,
  });
};

/**
 * Retrieves the open positions for a specific trading account.
 */
export const positionGetByTradingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PositionGetByTradingAccountData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    PositionGetByTradingAccountResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/all/account/{accountId}",
    ...options,
  });
};

/**
 * Retrieves the open positions for an account.
 */
export const positionGet = <ThrowOnError extends boolean = false>(
  options?: Options<PositionGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PositionGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position",
    ...options,
  });
};

/**
 * Retrieves the open positions for the current user.
 */
export const positionGetAllByUser = <ThrowOnError extends boolean = false>(
  options: Options<PositionGetAllByUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    PositionGetAllByUserResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Position/all/user/{userId}",
    ...options,
  });
};

export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const riskSettingsLockoutGet = <ThrowOnError extends boolean = false>(
  options: Options<RiskSettingsLockoutGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    RiskSettingsLockoutGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/RiskSettingsLockout/active/{tradingAccountId}",
    ...options,
  });
};

export const riskSettingsLockoutAddForDay = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RiskSettingsLockoutAddForDayData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RiskSettingsLockoutAddForDayResponses,
    unknown,
    ThrowOnError
  >({
    url: "/RiskSettingsLockout/addForDay",
    ...options,
  });
};

export const riskSettingsLockoutAdd = <ThrowOnError extends boolean = false>(
  options: Options<RiskSettingsLockoutAddData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RiskSettingsLockoutAddResponses,
    unknown,
    ThrowOnError
  >({
    url: "/RiskSettingsLockout/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const sessionValidate = <ThrowOnError extends boolean = false>(
  options?: Options<SessionValidateData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SessionValidateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Session/validate",
    ...options,
  });
};

/**
 * Generates a temporary SSO token for the specified user.
 */
export const singleSignOnGenerate = <ThrowOnError extends boolean = false>(
  options: Options<SingleSignOnGenerateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SingleSignOnGenerateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SingleSignOn/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Validates an SSO token and generates an authentication token for the user.
 */
export const singleSignOnLogin = <ThrowOnError extends boolean = false>(
  options: Options<SingleSignOnLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SingleSignOnLoginResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SingleSignOn/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetMonthly = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetMonthlyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetMonthlyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/monthly",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetWeekly = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetWeeklyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetWeeklyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/weekly",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetDaily = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetDailyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetDailyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/daily",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetProfitFactor = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetProfitFactorData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetProfitFactorResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/profitFactor",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetLifetimeStats = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StatisticsGetLifetimeStatsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetLifetimeStatsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/lifetimestats",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetDayStats = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetDayStatsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetDayStatsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/daystats",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetTodayStats = <ThrowOnError extends boolean = false>(
  options?: Options<StatisticsGetTodayStatsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    StatisticsGetTodayStatsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/todaystats",
    ...options,
  });
};

export const statisticsGetTradesForDay = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetTradesForDayData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetTradesForDayResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/daytrades",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetTradesForRange = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StatisticsGetTradesForRangeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetTradesForRangeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/trades",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsGetWinLossAvg = <ThrowOnError extends boolean = false>(
  options: Options<StatisticsGetWinLossAvgData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsGetWinLossAvgResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/winlossavg",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsSetAccountSharing = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StatisticsSetAccountSharingData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StatisticsSetAccountSharingResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/setSharing",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const statisticsCheckAccountSharing = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<StatisticsCheckAccountSharingData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StatisticsCheckAccountSharingResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/checkSharing",
    ...options,
  });
};

export const statisticsGetAccountName = <ThrowOnError extends boolean = false>(
  options?: Options<StatisticsGetAccountNameData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StatisticsGetAccountNameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Statistics/getAccountName",
    ...options,
  });
};

export const studyTemplatesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<StudyTemplatesGetAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StudyTemplatesGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/study-templates/all",
    ...options,
  });
};

export const studyTemplatesRemoveByName = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StudyTemplatesRemoveByNameData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    StudyTemplatesRemoveByNameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/study-templates/removeByName/{name}",
    ...options,
  });
};

export const studyTemplatesSaveStudyTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StudyTemplatesSaveStudyTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    StudyTemplatesSaveStudyTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/study-templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const studyTemplatesGetStudyTemplate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StudyTemplatesGetStudyTemplateData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    StudyTemplatesGetStudyTemplateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/study-templates/content/{studyTemplateName}",
    ...options,
  });
};

export const symbolBlockGetAll = <ThrowOnError extends boolean = false>(
  options: Options<SymbolBlockGetAllData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    SymbolBlockGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SymbolBlock/all/{accountId}",
    ...options,
  });
};

export const symbolBlockSet = <ThrowOnError extends boolean = false>(
  options: Options<SymbolBlockSetData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SymbolBlockSetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SymbolBlock/set",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const symbolBlockAdd = <ThrowOnError extends boolean = false>(
  options: Options<SymbolBlockAddData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SymbolBlockAddResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SymbolBlock/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const symbolBlockRemove = <ThrowOnError extends boolean = false>(
  options: Options<SymbolBlockRemoveData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    SymbolBlockRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: "/SymbolBlock/remove",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tiltActivate = <ThrowOnError extends boolean = false>(
  options?: Options<TiltActivateData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TiltActivateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Tilt/activate",
    ...options,
  });
};

export const tiltActivateWithAccountId = <ThrowOnError extends boolean = false>(
  options: Options<TiltActivateWithAccountIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    TiltActivateWithAccountIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Tilt/activate/{accountId}",
    ...options,
  });
};

export const tradeClockSetTradeClock = <ThrowOnError extends boolean = false>(
  options: Options<TradeClockSetTradeClockData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeClockSetTradeClockResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradeClock",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Retrieves a list of filled trades for an account.
 */
export const tradeGet = <ThrowOnError extends boolean = false>(
  options: Options<TradeGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    TradeGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Trade/id/{accountId}",
    ...options,
  });
};

export const tradeGetInRange = <ThrowOnError extends boolean = false>(
  options: Options<TradeGetInRangeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeGetInRangeResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Trade/range",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tradeUserExportJson = <ThrowOnError extends boolean = false>(
  options: Options<TradeUserExportJsonData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeUserExportJsonResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Trade/user/export/json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tradeUserExportCsv = <ThrowOnError extends boolean = false>(
  options: Options<TradeUserExportCsvData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeUserExportCsvResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Trade/user/export/csv",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tradeLimitAddTradeLimits = <ThrowOnError extends boolean = false>(
  options: Options<TradeLimitAddTradeLimitsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeLimitAddTradeLimitsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradeLimit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Retrieves all accounts associated with the current user.
 */
export const tradingAccountGet = <ThrowOnError extends boolean = false>(
  options?: Options<TradingAccountGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TradingAccountGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount",
    ...options,
  });
};

export const tradingAccountSetAccountNickname = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountSetAccountNicknameData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradingAccountSetAccountNicknameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Sets the personal daily loss limit for an account.
 */
export const tradingAccountSetPersonalDailyLossLimit = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountSetPersonalDailyLossLimitData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    TradingAccountSetPersonalDailyLossLimitResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/pdll/{accountId}",
    ...options,
  });
};

export const tradingAccountSetPersonalDailyLimits = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountSetPersonalDailyLimitsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradingAccountSetPersonalDailyLimitsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/personalLimits",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Follows the trades made by another account.
 */
export const tradingAccountFollow = <ThrowOnError extends boolean = false>(
  options: Options<TradingAccountFollowData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradingAccountFollowResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/follow",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Unfollows an account that is following another account and liquidates the account.
 */
export const tradingAccountUnfollow = <ThrowOnError extends boolean = false>(
  options?: Options<TradingAccountUnfollowData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    TradingAccountUnfollowResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/unfollow",
    ...options,
  });
};

/**
 * Clears all followers from an account.
 */
export const tradingAccountClearFollowers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountClearFollowersData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    TradingAccountClearFollowersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/followers/clear/{tradingAccountId}",
    ...options,
  });
};

/**
 * Retrieves a list of following accounts for the current user.
 */
export const tradingAccountGetFollowEntries = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TradingAccountGetFollowEntriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TradingAccountGetFollowEntriesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/followers",
    ...options,
  });
};

/**
 * Immediately stops all trading and liquidates the account. A "personal stop" violation will be added to the account for informational purposes.
 */
export const tradingAccountStopTrading = <ThrowOnError extends boolean = false>(
  options: Options<TradingAccountStopTradingData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    TradingAccountStopTradingResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/stopTrading/{tradingAccountId}",
    ...options,
  });
};

/**
 * Sets the position brackets for a trading account.
 */
export const tradingAccountSetPositionBrackets = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountSetPositionBracketsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradingAccountSetPositionBracketsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/setPositionBrackets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Sets the AutoOcoBrackets flag for a trading account.
 */
export const tradingAccountSetAutoOcoBrackets = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TradingAccountSetAutoOcoBracketsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradingAccountSetAutoOcoBracketsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccount/setAutoOcoBrackets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tradingAccountStateLogGetTradingAccountStateLog = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TradingAccountStateLogGetTradingAccountStateLogData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    TradingAccountStateLogGetTradingAccountStateLogResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingAccountStateLog",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const tradingRuleGetTradingRules = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TradingRuleGetTradingRulesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TradingRuleGetTradingRulesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/TradingRule",
    ...options,
  });
};

export const userAgreementGet = <ThrowOnError extends boolean = false>(
  options?: Options<UserAgreementGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserAgreementGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserAgreement",
    ...options,
  });
};

export const userAgreementSign = <ThrowOnError extends boolean = false>(
  options: Options<UserAgreementSignData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserAgreementSignResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserAgreement/sign",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userAgreementLegacyGetRequired = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserAgreementLegacyGetRequiredData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserAgreementLegacyGetRequiredResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserAgreement/signed",
    ...options,
  });
};

export const userAgreementGetRequired = <ThrowOnError extends boolean = false>(
  options?: Options<UserAgreementGetRequiredData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserAgreementGetRequiredResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserAgreement/signed/v2",
    ...options,
  });
};

/**
 * Returns a list of all contracts available (for stat sharing)
 */
export const userContractGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserContractGetAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserContractGetAllResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserContract/all",
    ...options,
  });
};

/**
 * Gets a list of all active contracts allowed for the currently logged-in user (non-professional)
 */
export const userContractGetNonProfessional = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserContractGetNonProfessionalData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserContractGetNonProfessionalResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserContract/active/nonprofesional",
    ...options,
  });
};

/**
 * Gets a list of all active contracts allowed for the currently logged-in user (professional only - live)
 */
export const userContractGetProfessional = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserContractGetProfessionalData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserContractGetProfessionalResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserContract/active/professional",
    ...options,
  });
};

/**
 * Retrieves details about the current user.
 */
export const userGet = <ThrowOnError extends boolean = false>(
  options?: Options<UserGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User",
    ...options,
  });
};

/**
 * Updates the agreement status for a specific user or the current user if no user ID is provided.
 */
export const userPutAgreementsCompleted = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserPutAgreementsCompletedData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UserPutAgreementsCompletedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/agreementsCompleted",
    ...options,
  });
};

export const userGetIntercomHash = <ThrowOnError extends boolean = false>(
  options?: Options<UserGetIntercomHashData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserGetIntercomHashResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/intercom/hash",
    ...options,
  });
};

/**
 * Creates a new API key for the current user.
 */
export const userCreateApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<UserCreateApiKeyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserCreateApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/createApiKey",
    ...options,
  });
};

export const userRevokeApiKey = <ThrowOnError extends boolean = false>(
  options: Options<UserRevokeApiKeyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserRevokeApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/revokeApiKey",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userGetApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<UserGetApiKeysData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserGetApiKeysResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/apiKeys",
    ...options,
  });
};

export const userGetDashboardLinkUrl = <ThrowOnError extends boolean = false>(
  options?: Options<UserGetDashboardLinkUrlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserGetDashboardLinkUrlResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/dashboardLink",
    ...options,
  });
};

/**
 * Returns the time in UTC.
 * Used to ensure clock synchronization between the client and the server.
 */
export const userGetCurrentTimeUtc = <ThrowOnError extends boolean = false>(
  options?: Options<UserGetCurrentTimeUtcData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserGetCurrentTimeUtcResponses,
    unknown,
    ThrowOnError
  >({
    url: "/User/currentTimeUtc",
    ...options,
  });
};

export const userDataUploadUploadUserData = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserDataUploadUploadUserDataData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UserDataUploadUploadUserDataResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/UserDataUpload",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
  });
};

export const userNotificationGetUnreadNotifications = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserNotificationGetUnreadNotificationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserNotificationGetUnreadNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserNotification",
    ...options,
  });
};

export const userNotificationReadNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserNotificationReadNotificationData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserNotificationReadNotificationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserNotification/read",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userRoleGetAvailableRoles = <ThrowOnError extends boolean = false>(
  options?: Options<UserRoleGetAvailableRolesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserRoleGetAvailableRolesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserRole/roles",
    ...options,
  });
};

export const userRoleGetUserRolesByUserId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserRoleGetUserRolesByUserIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UserRoleGetUserRolesByUserIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserRole/{userId}",
    ...options,
  });
};

export const userRoleGetRolesByUserId = <ThrowOnError extends boolean = false>(
  options: Options<UserRoleGetRolesByUserIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UserRoleGetRolesByUserIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserRole/{userId}/roles",
    ...options,
  });
};

export const userRoleHasUserRole = <ThrowOnError extends boolean = false>(
  options: Options<UserRoleHasUserRoleData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UserRoleHasUserRoleResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserRole/{userId}/has/{roleId}",
    ...options,
  });
};

export const userSettingsGet = <ThrowOnError extends boolean = false>(
  options?: Options<UserSettingsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UserSettingsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserSettings",
    ...options,
  });
};

export const userSettingsPost = <ThrowOnError extends boolean = false>(
  options: Options<UserSettingsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserSettingsPostResponses,
    unknown,
    ThrowOnError
  >({
    url: "/UserSettings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const userSettingsPostV2 = <ThrowOnError extends boolean = false>(
  options: Options<UserSettingsPostV2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UserSettingsPostV2Responses,
    unknown,
    ThrowOnError
  >({
    url: "/UserSettings/v2",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const violationsGetActiveViolation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ViolationsGetActiveViolationData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ViolationsGetActiveViolationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/Violations/active/{tradingAccountId}",
    ...options,
  });
};
