// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * 0 = None
 * 1 = Practice
 * 2 = Funded
 */
export const zTag = z.union([z.literal(0), z.literal(1), z.literal(2)]);

export const zAccountTemplateModel = z.object({
  id: z.int(),
  title: z.string(),
  titleColor: z.optional(z.string()),
  description: z.optional(z.string()),
  startingBalance: z.number(),
  margin: z.number(),
  tag: zTag,
  limitCopyTradingToTemplate: z.boolean(),
  copyTradingGroup: z.optional(z.string()),
});

/**
 * 0 = Undefined
 * 1 = DailyLossLimit
 * 2 = MaximumLossLimit
 * 3 = MarginScale
 */
export const zTradingRuleType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

/**
 * 0 = Active
 * 1 = TemporaryViolation
 * 2 = Violation
 * 3 = Inactive
 * 4 = Closed
 * 5 = GoalAchieved
 * 6 = Ineligible
 * 7 = Paused
 */
export const zTradingAccountStatus = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

/**
 * 0 = Unspecified
 * 1 = Permanent
 * 2 = Temporary
 */
export const zViolationDuration = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

/**
 * 0 = None
 * 1 = StartingBalance
 * 2 = StartOfDayBalance
 * 3 = CurrentBalance
 * 4 = GoalBalance
 * 5 = HighestBalance
 * 6 = HighestUnrealizedBalance
 * 7 = HighestRealizedBalance
 * 8 = SpecifiedBalance
 */
export const zBalanceSource = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

export const zDailyLossLimitConfiguration = z.object({
  source: zBalanceSource,
  percentage: z.optional(z.number()),
  limit: z.optional(z.number()),
  disableBalanceSource: z.optional(zBalanceSource),
  disableCheckSource: z.optional(zBalanceSource),
  disablePercentage: z.optional(z.number()),
  disableLimit: z.optional(z.number()),
  disableMinimumBalanceSource: z.optional(zBalanceSource),
  disableMaximumBalanceSource: z.optional(zBalanceSource),
});

export const zMaximumLossLimitConfiguration = z.object({
  source: zBalanceSource,
  percentage: z.optional(z.number()),
  limit: z.optional(z.number()),
  minimumSource: z.optional(zBalanceSource),
  maximumSource: z.optional(zBalanceSource),
  maximumSourceSpecifiedBalance: z.optional(z.number()),
});

/**
 * 0 = EndOfDay
 */
export const zMarginScaleTime = z.literal(0);

/**
 * 0 = RealizedDayPnl
 * 1 = EndOfDayBalance
 */
export const zProfitSource = z.union([z.literal(0), z.literal(1)]);

export const zScaleValue = z.object({
  minValue: z.number(),
  maxValue: z.number(),
  source: zProfitSource,
  margin: z.number(),
});

export const zMarginScaleConfiguration = z.object({
  time: zMarginScaleTime,
  values: z.optional(z.array(zScaleValue)),
});

export const zRuleConfiguration = z.object({
  violationStatus: z.optional(zTradingAccountStatus),
  violationDuration: z.optional(zViolationDuration),
  liquidateFollowers: z.optional(z.boolean()),
  dailyLossLimit: z.optional(zDailyLossLimitConfiguration),
  maximumLossLimit: z.optional(zMaximumLossLimitConfiguration),
  marginScale: z.optional(zMarginScaleConfiguration),
});

export const zAccountTemplateRuleModel = z.object({
  accountTemplateId: z.int(),
  ruleId: zTradingRuleType,
  configuration: zRuleConfiguration,
});

/**
 * 0 = Unknown
 * 1 = Limit
 * 2 = Market
 * 3 = StopLimit
 * 4 = Stop
 * 5 = TrailingStop
 * 6 = JoinBid
 * 7 = JoinAsk
 */
export const zOrderType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

/**
 * 0 = Tick
 * 1 = Dollar
 */
export const zAutoOcoBracketValueType = z.union([z.literal(0), z.literal(1)]);

export const zAutoOcoBracketModel = z.object({
  id: z.int(),
  name: z.string(),
  takeProfitValue: z.optional(z.number()),
  stopLossValue: z.optional(z.number()),
  takeProfitType: z.optional(zOrderType),
  stopLossType: z.optional(zOrderType),
  takeProfitValueType: zAutoOcoBracketValueType,
  stopLossValueType: zAutoOcoBracketValueType,
  updatedAt: z.iso.datetime(),
});

/**
 * Specifies the error codes for AutoOcoBracket operations.
 *
 * 0 = Success
 * 1 = Unauthorized
 * 2 = InvalidStopLossTicks
 * 3 = InvalidTakeProfitTicks
 * 4 = InvalidStopLossType
 * 5 = InvalidTakeProfitType
 * 6 = BracketAlreadyExists
 * 7 = NoBracketOrdersProvided
 * 8 = UnknownError
 * 9 = InvalidName
 * 10 = NameAlreadyExists
 */
export const zAutoOcoBracketErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
  z.literal(9),
  z.literal(10),
]);

/**
 * Represents a response from an AutoOcoBracket operation.
 */
export const zAutoOcoBracketResponse = z.object({
  success: z.boolean(),
  errorCode: zAutoOcoBracketErrorCode,
  errorMessage: z.optional(z.string()),
  bracket: z.optional(zAutoOcoBracketModel),
});

/**
 * Represents a request to create or update an AutoOcoBracket.
 */
export const zAutoOcoBracketRequest = z.object({
  id: z.optional(z.int()),
  name: z.string(),
  stopLossValue: z.optional(z.number()),
  takeProfitValue: z.optional(z.number()),
  stopLossType: z.optional(zOrderType),
  takeProfitType: z.optional(zOrderType),
  stopLossValueType: zAutoOcoBracketValueType,
  takeProfitValueType: zAutoOcoBracketValueType,
});

/**
 * Specifies the error codes for AutoOcoBracket removal operations.
 *
 * 0 = Success
 * 1 = Unauthorized
 * 2 = BracketNotFound
 * 3 = BracketAlreadyDeleted
 * 4 = UnknownError
 */
export const zAutoOcoBracketRemoveErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

/**
 * Represents a response from an AutoOcoBracket removal operation.
 */
export const zAutoOcoBracketRemoveResponse = z.object({
  success: z.boolean(),
  errorCode: zAutoOcoBracketRemoveErrorCode,
  errorMessage: z.optional(z.string()),
  removedBracketId: z.optional(z.int()),
});

/**
 * Represents a request to remove an AutoOcoBracket.
 */
export const zAutoOcoBracketRemoveRequest = z.object({
  bracketId: z.int(),
});

export const zChartResult = z.object({
  status: z.string(),
  id: z.optional(z.int()),
  data: z.unknown(),
});

export const zChartBaseModel = z.object({
  id: z.optional(z.string()),
  name: z.string(),
  symbol: z.string(),
  resolution: z.string(),
});

export const zChartSummaryModel = zChartBaseModel.and(
  z.object({
    timestamp: z.iso.datetime(),
  }),
);

export const zChartModel = zChartBaseModel.and(
  z.object({
    content: z.string(),
  }),
);

export const zChartTemplateModel = z.object({
  id: z.int(),
  userId: z.int(),
  name: z.string(),
  content: z.string(),
});

export const zRiskContractLimitModel = z.object({
  id: z.int(),
  symbolId: z.string(),
  limit: z.int(),
  accountId: z.int(),
});

export const zSetRiskContractLimitsResult = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zSetRiskContractLimitModel = z.object({
  symbolId: z.string(),
  limit: z.int(),
});

export const zSetRiskContractLimitsRequest = z.object({
  accountId: z.int(),
  limits: z.array(zSetRiskContractLimitModel),
});

export const zDrawingTemplateModel = z.object({
  id: z.int(),
  userId: z.int(),
  content: z.string(),
  toolName: z.string(),
  templateName: z.string(),
});

export const zRemoveDrawingTemplateRequest = z.object({
  toolName: z.string(),
  templateName: z.string(),
});

export const zGetDrawingTemplateRequest = z.object({
  toolName: z.string(),
  templateName: z.string(),
});

/**
 * 0 = Success
 * 1 = InvalidToken
 * 2 = InvalidPassword
 * 3 = InvalidUsername
 * 4 = Failed
 * 5 = Pending
 */
export const zPasswordResetResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zPasswordResetRequest = z.object({
  userName: z.string(),
  token: z.string(),
  password: z.string(),
});

/**
 * 0 = Inserted
 * 1 = Updated
 * 2 = TradingAccountNotFound
 * 3 = TradeNotFound
 * 4 = AccountMismatch
 * 5 = TradeDayMismatch
 * 6 = ContentTooLarge
 * 7 = Forbidden
 */
export const zJournalUpsertResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

export const zJournalLogUpsertResponse = z.object({
  success: z.boolean(),
  resultCode: zJournalUpsertResult,
});

export const zJournalLogUpsertRequest = z.object({
  tradingAccountId: z.int(),
  tradeId: z.optional(z.coerce.bigint()),
  tradeDay: z.iso.datetime(),
  content: z.string().max(10240),
});

export const zJournalLog = z.object({
  tradingAccountId: z.int(),
  tradeId: z.optional(z.coerce.bigint()),
  tradeDay: z.iso.datetime(),
  content: z.string(),
});

export const zGetJournalLogDayRequest = z.object({
  tradingAccountId: z.int(),
  tradeDay: z.iso.datetime(),
});

export const zGetJournalLogTradeRequest = z.object({
  tradingAccountId: z.int(),
  tradeId: z.coerce.bigint(),
});

export const zGetJournalLogRangeRequest = z.object({
  tradingAccountId: z.int(),
  startDate: z.iso.datetime(),
  endDate: z.iso.datetime(),
});

export const zDeleteJournalLogRequest = z.object({
  tradingAccountId: z.int(),
  tradeDay: z.iso.datetime(),
  tradeId: z.optional(z.coerce.bigint()),
});

export const zJsonDocument = z.object({
  isDisposable: z.boolean(),
  rootElement: z.unknown(),
});

export const zLayoutModel = z.object({
  id: z.int(),
  name: z.string(),
  content: zJsonDocument,
  createdAt: z.iso.datetime(),
  isDraft: z.boolean(),
});

export const zLineToolsModel = z.object({
  id: z.int(),
  userId: z.int(),
  layoutId: z.string(),
  chartId: z.string(),
  symbol: z.optional(z.string()),
  sources: z.string(),
  groups: z.string(),
});

/**
 * 0 = Success
 * 1 = Exception
 * 2 = InvalidOrder
 * 3 = MultipleSymbols
 * 4 = AlreadyLinked
 * 5 = InvalidLinkGroup
 * 6 = InvalidTradingAccount
 * 7 = InvalidAccountType
 */
export const zLinkOrderUserResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

export const zUnlinkOrderUserResponse = z.object({
  orderIds: z.array(z.coerce.bigint()),
  result: zLinkOrderUserResult,
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zUnlinkOrderUserRequest = z.object({
  tradingAccountId: z.int(),
  groupId: z.string(),
});

export const zLinkedOrderModel = z.object({
  tradingAccountId: z.int(),
  groupId: z.string(),
  linkedOrderIds: z.array(z.coerce.bigint()),
});

export const zGetLinkedOrdersResponse = z.object({
  linkedOrders: z.array(zLinkedOrderModel),
});

export const zLinkOrderUserResponse = z.object({
  result: zLinkOrderUserResult,
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zLinkOrderUserRequest = z.object({
  tradingAccountId: z.int(),
  orderIds: z.array(z.coerce.bigint()),
});

/**
 * 0 = Success
 * 1 = InvalidUsername
 * 2 = InvalidPassword
 * 3 = Inactive
 * 4 = LockedOut
 * 5 = Requires2FA
 * 6 = RequirePwChange
 */
export const zLoginResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

export const zLoginResultModel = z.object({
  result: zLoginResult,
  token: z.optional(z.string()),
  twoFaToken: z.optional(z.string()),
});

export const zLoginRequestModel = z.object({
  userName: z.string(),
  password: z.string(),
});

export const zApiKeyLoginRequest = z.object({
  userName: z.string(),
  apiKey: z.string(),
});

export const zMarketClosureModel = z.object({
  id: z.int(),
  startTime: z.iso.datetime(),
  endTime: z.iso.datetime(),
  name: z.string(),
  description: z.string(),
});

export const zMarketStatusSummary = z.object({
  isOpen: z.boolean(),
  nextOpen: z.iso.datetime(),
  close: z.iso.datetime(),
});

/**
 * 1 = PreOpen
 * 2 = Open
 * 3 = Closed
 * 4 = Halted
 * 5 = Suspended
 */
export const zExchangeStatus = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zMarketStatus = z.object({
  symbolId: z.string(),
  status: zExchangeStatus,
  simStatus: zExchangeStatus,
  openedAt: z.iso.datetime(),
  autoLiquidate: z.boolean(),
  isOpen: z.boolean(),
});

/**
 * 0 = Success
 * 1 = ContractGroupNotFound
 */
export const zSetMarketStatusErrorCode = z.union([z.literal(0), z.literal(1)]);

export const zSetMarketStatusResponse = z.object({
  success: z.boolean(),
  errorCode: zSetMarketStatusErrorCode,
  contractGroupId: z.string(),
  errorMessage: z.optional(z.string()),
});

export const zSetSingleMarketStatusRequest = z.object({
  contractGroupId: z.string(),
  status: zExchangeStatus,
});

export const zSetManyMarketStatusResponse = z.object({
  success: z.boolean(),
  responses: z.array(zSetMarketStatusResponse),
});

export const zSetManyMarketStatusRequest = z.object({
  status: zExchangeStatus,
});

export const zResetSingleMarketStatusRequest = z.object({
  contractGroupId: z.string(),
});

export const zSymbolMetadata = z.object({
  symbol: z.string(),
  friendlyName: z.string(),
  fullName: z.string(),
  description: z.string(),
  maturityMonthYear: z.string(),
  contractId: z.int(),
  tickSize: z.number(),
  tickValue: z.number(),
  contractCost: z.number(),
  fees: z.number(),
  marketGroupId: z.number(),
  decimalPlaces: z.int(),
  priceScale: z.number(),
  minMove: z.number(),
  fractionalPrice: z.boolean(),
  exchange: z.string(),
  minMove2: z.number(),
  disabled: z.boolean(),
});

export const zMigratePartialChartsRequest = z.object({
  startId: z.int(),
  endId: z.int(),
});

export const zMigrateChartsRequest = z.object({
  totalUsers: z.int(),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = InvalidSecret
 * 3 = InvalidToken
 * 4 = AlreadyEnabled
 * 5 = NotAvailable
 * 6 = InvalidNonce
 */
export const zCreateMfaErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

/**
 * 0 = Authenticator
 * 1 = Email
 */
export const zMfaMethod = z.union([z.literal(0), z.literal(1)]);

export const zCreate2FaRequest = z.object({
  secret: z.string(),
  token: z.string(),
  nonce: z.optional(z.string()),
  method: z.optional(zMfaMethod),
});

export const zCreateRecoveryCodesResult = z.object({
  token: z.optional(z.string()),
  errorCode: z.optional(zCreateMfaErrorCode),
  recoveryCodes: z.optional(z.array(z.string())),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = TotpTokenNotFound
 * 3 = InvalidToken
 */
export const zSubmit2FaErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

export const zSubmit2FaResult = z.object({
  token: z.optional(z.string()),
  errorCode: z.optional(zSubmit2FaErrorCode),
});

export const zVerify2FaRequest = z.object({
  nonceToken: z.string(),
  code: z.string(),
  method: zMfaMethod,
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = RecoveryCodeAlreadyUsed
 * 3 = InvalidRecoveryCode
 */
export const zSubmitRecoveryErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

export const zSubmitRecoveryCodeResult = z.object({
  token: z.optional(z.string()),
  errorCode: z.optional(zSubmitRecoveryErrorCode),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 */
export const zRegenerateRecoveryCodeErrorCode = z.union([
  z.literal(0),
  z.literal(1),
]);

export const zRegenerateRecoveryCodesResult = z.object({
  recoveryCodes: z.optional(z.array(z.string())),
  errorCode: z.optional(zRegenerateRecoveryCodeErrorCode),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = TokenAlreadyDisabled
 * 3 = TokenDoesntExist
 */
export const zDisable2FaErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

export const zRequestEmailCodeResult = z.object({
  nonce: z.string(),
});

export const zRequestEmailCodeModel = z.object({
  nonce: z.string(),
  initialSetup: z.optional(z.boolean()),
});

/**
 * 0 = NotAvailable
 * 1 = AvailableNotConfigured
 * 2 = AvailableAndConfigured
 */
export const zMfaAvailabilityStatus = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zHasMfaResult = z.object({
  methods: z.record(z.string(), zMfaAvailabilityStatus),
});

export const zHasMfaRequest = z.object({
  nonce: z.optional(z.string()),
});

export const zUserAgreementModel = z.object({
  id: z.int(),
  title: z.string(),
  url: z.string(),
  customAcceptText: z.optional(z.string()),
  isProfessional: z.boolean(),
  updatedAt: z.iso.datetime(),
  agreementKey: z.optional(z.string()),
});

/**
 * 0 = None
 * 1 = Password
 * 2 = MultiFactorAuth
 * 3 = Subscription
 * 4 = Agreements
 * 5 = Completed
 */
export const zOnboardingState = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zOnboardingDataModel = z.object({
  userName: z.string(),
  email: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  requiredAgreements: z.array(zUserAgreementModel),
  availableSubscriptions: z.array(z.string()),
  onboardingRequired: z.boolean(),
  onboardingState: zOnboardingState,
});

export const zRequestEmailCodeResponse = z.object({
  nonce: z.string(),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = InvalidStepOrder
 * 3 = InvalidPassword
 * 4 = PasswordUpdateFailed
 * 5 = DatabaseError
 */
export const zSetPasswordErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zSetPasswordResponse = z.object({
  success: z.boolean(),
  errorCode: zSetPasswordErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zSetPasswordRequest = z.object({
  password: z.string(),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = InvalidStepOrder
 * 3 = InvalidMfaSecret
 * 4 = MfaAlreadyEnabled
 * 5 = MfaSetupFailed
 * 6 = InvalidToken
 * 7 = InvalidNonce
 * 8 = DatabaseError
 */
export const zSetupMfaErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

export const zSetupMfaResponse = z.object({
  success: z.boolean(),
  errorCode: zSetupMfaErrorCode,
  errorMessage: z.optional(z.string()),
  recoveryCodes: z.optional(z.array(z.string())),
});

export const zSetupMfaRequest = z.object({
  method: zMfaMethod,
  token: z.optional(z.string()),
  authSecret: z.optional(z.string()),
  nonce: z.optional(z.string()),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = InvalidStepOrder
 * 3 = SubscriptionCreationFailed
 * 4 = DatabaseError
 */
export const zCreateSubscriptionErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zCreateSubscriptionResponse = z.object({
  success: z.boolean(),
  errorCode: zCreateSubscriptionErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zCreateSubscriptionRequest = z.object({
  subscriptionId: z.optional(z.string()),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = InvalidStepOrder
 * 3 = AgreementsSigningFailed
 * 4 = DatabaseError
 */
export const zSignAgreementsErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zSignAgreementsResponse = z.object({
  success: z.boolean(),
  errorCode: zSignAgreementsErrorCode,
  errorMessage: z.optional(z.string()),
  authToken: z.optional(z.string()),
});

export const zSignAgreementRequest = z.object({
  agreementIds: z.array(z.int()),
  name: z.string(),
  streetAddress: z.string(),
  city: z.string(),
  state: z.string(),
  zipCode: z.string(),
  countryCode: z.string(),
  country: z.string(),
});

/**
 * 0 = None
 * 1 = Open
 * 2 = Filled
 * 3 = Cancelled
 * 4 = Expired
 * 5 = Rejected
 * 6 = Pending
 * 7 = PendingCancellation
 * 8 = Suspended
 */
export const zOrderStatus = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

/**
 * 0 = Day
 * 1 = GoodTillCancelled
 */
export const zTimeType = z.union([z.literal(0), z.literal(1)]);

export const zOrderModel = z.object({
  id: z.coerce.bigint(),
  symbolId: z.string(),
  symbolName: z.string(),
  accountId: z.int(),
  limitPrice: z.optional(z.number()),
  stopPrice: z.optional(z.number()),
  executePrice: z.optional(z.number()),
  createdAt: z.iso.datetime(),
  tradeDay: z.iso.datetime(),
  filledAt: z.optional(z.iso.datetime()),
  cancelledAt: z.optional(z.iso.datetime()),
  status: zOrderStatus,
  type: zOrderType,
  positionSize: z.int(),
  rejectionReason: z.optional(z.string()),
  customTag: z.optional(z.string()),
  trailDistance: z.optional(z.int()),
  contractId: z.string(),
  contractName: z.string(),
  totalFilled: z.int(),
  exchangeOrderId: z.optional(z.string()),
  platformOrderId: z.optional(z.string()),
  timeType: z.optional(zTimeType),
  parentOrderId: z.optional(z.coerce.bigint()),
  linkedOrderId: z.optional(z.coerce.bigint()),
});

/**
 * 0 = Filled
 * 1 = Queued
 * 2 = Rejected
 * 3 = InsufficientFunds
 * 4 = Violation
 * 5 = OutsideTradingHours
 * 6 = Pending
 */
export const zPlaceOrderResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

/**
 * 0 = Undetermined
 * 1 = Opening
 * 2 = Closing
 */
export const zOrderPositionDisposition = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zPlaceOrderResponse = z.object({
  result: zPlaceOrderResult,
  positionDisposition: zOrderPositionDisposition,
  orderId: z.optional(z.coerce.bigint()),
  executedPrice: z.optional(z.number()),
  errorMessage: z.optional(z.string()),
});

export const zPlaceOrderBracket = z.object({
  ticks: z.int(),
  type: zOrderType,
});

export const zPlaceOrderRequest = z.object({
  accountId: z.int(),
  symbolId: z.string(),
  type: zOrderType,
  limitPrice: z.optional(z.number()),
  stopPrice: z.optional(z.number()),
  trailDistance: z.optional(z.int()),
  positionSize: z.int(),
  customTag: z.optional(z.string()),
  linkedOrderId: z.optional(z.coerce.bigint()),
  contractId: z.optional(z.string()),
  timeType: zTimeType,
  stopLoss: z.optional(zPlaceOrderBracket),
  takeProfit: z.optional(zPlaceOrderBracket),
});

/**
 * 0 = Bid
 * 1 = Ask
 */
export const zOrderSide = z.union([z.literal(0), z.literal(1)]);

/**
 * 0 = Undetermined
 * 1 = StopLoss
 * 2 = TakeProfit
 * 3 = ClosePosition
 * 4 = ReversePosition
 * 5 = Trader
 */
export const zOrderCreationDisposition = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zOrderExportModel = z.object({
  id: z.coerce.bigint(),
  accountName: z.string(),
  contractName: z.string(),
  status: zOrderStatus,
  type: zOrderType,
  size: z.int(),
  side: zOrderSide,
  createdAt: z.iso.datetime(),
  tradeDay: z.iso.datetime(),
  filledAt: z.optional(z.iso.datetime()),
  cancelledAt: z.optional(z.iso.datetime()),
  stopPrice: z.optional(z.number()),
  limitPrice: z.optional(z.number()),
  executePrice: z.optional(z.number()),
  positionDisposition: zOrderPositionDisposition,
  creationDisposition: zOrderCreationDisposition,
  rejectionReason: z.optional(z.string()),
  exchangeOrderId: z.optional(z.string()),
  platformOrderId: z.optional(z.string()),
});

export const zUserExportRequest = z.object({
  tradingAccountId: z.int(),
  start: z.iso.datetime(),
  end: z.iso.datetime(),
  timeZone: z.optional(z.string()),
});

export const zUpdateStopLossResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
});

export const zUpdateStopLossAccountRequest = z.object({
  tradingAccountId: z.int(),
  positionId: z.int(),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
  timeType: zTimeType,
});

export const zUpdateStopLossRequest = z.object({
  positionId: z.int(),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
  timeType: zTimeType,
});

/**
 * 0 = Unknown
 * 1 = Personal
 * 2 = WeeklyTradeLimit
 * 3 = DailyTradeLimit
 * 4 = TradeClock
 */
export const zPersonalLockoutType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zPersonalLockoutModel = z.object({
  id: z.int(),
  tradingAccountId: z.int(),
  userId: z.int(),
  reason: z.optional(z.string()),
  shouldLiquidate: z.boolean(),
  createdAt: z.iso.datetime(),
  tradeDay: z.iso.datetime(),
  startsAt: z.iso.datetime(),
  expiresAt: z.iso.datetime(),
  type: zPersonalLockoutType,
});

export const zSetPersonalLockoutResult = z.object({
  id: z.int(),
  message: z.string(),
  success: z.boolean(),
});

/**
 * 0 = Trader
 * 1 = System
 * 2 = Admin
 */
export const zLegacyOrderCancellationSource = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zStopLossTakeProfitModel = z.object({
  positionId: z.int(),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
  errorMessage: z.optional(z.string()),
  cancellationSource: zLegacyOrderCancellationSource,
});

/**
 * 0 = Success
 * 1 = PositionNotFound
 * 2 = InvalidStopLoss
 * 3 = InvalidTakeProfit
 * 4 = TradingDisabled
 * 5 = FollowAccount
 * 6 = PositionBracketsDisabled
 */
export const zUpdateStopLossTakeProfitErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

export const zUpdateStopLossTakeProfitResult = z.object({
  positionId: z.int(),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
  errorCode: zUpdateStopLossTakeProfitErrorCode,
});

export const zPositionModel = z.object({
  id: z.int(),
  symbolId: z.string(),
  symbolName: z.string(),
  positionSize: z.int(),
  stopLoss: z.optional(z.number()),
  takeProfit: z.optional(z.number()),
  toMake: z.optional(z.number()),
  risk: z.optional(z.number()),
  averagePrice: z.number(),
  profitAndLoss: z.number(),
  entryTime: z.iso.datetime(),
  accountId: z.int(),
  stopLossOrderId: z.optional(z.coerce.bigint()),
  takeProfitOrderId: z.optional(z.coerce.bigint()),
  contractId: z.optional(z.string()),
});

/**
 * 0 = Success
 * 1 = UsernameTaken
 * 2 = EmailTaken
 * 3 = InvalidEmail
 * 4 = InvalidPassword
 */
export const zRegisterResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zRegisterResponse = z.object({
  userId: z.optional(z.int()),
  loginToken: z.optional(z.string()),
  errorMessage: z.optional(z.string()),
  result: zRegisterResult,
});

/**
 * 0 = Default
 * 1 = Internal
 */
export const zUserInternalTag = z.union([z.literal(0), z.literal(1)]);

export const zRegisterRequest = z.object({
  password: z.string(),
  email: z.string(),
  userName: z.optional(z.string()),
  firstName: z.optional(z.string()),
  lastName: z.optional(z.string()),
  screenName: z.optional(z.string()),
  internalTag: z.optional(zUserInternalTag),
  requireOnboarding: z.optional(z.boolean()),
});

/**
 * 0 = Sim
 * 10 = CTS
 */
export const zPlatformId = z.union([z.literal(0), z.literal(10)]);

/**
 * 0 = None
 * 1 = UnrealizedGains
 * 2 = RealizedGains
 */
export const zPersonalDailyLossLimitTrailingType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

/**
 * 0 = None
 * 1 = Liquidate
 * 2 = LiquidateAndBlock
 */
export const zPersonalDailyAction = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

/**
 * 0 = None
 * 1 = Sim
 * 2 = Live
 * 3 = Express
 * 4 = Practice
 */
export const zTradingAccountType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

/**
 * 0 = Default
 * 1 = Internal
 */
export const zTradingAccountInternalTag = z.union([z.literal(0), z.literal(1)]);

export const zTradingAccount = z.object({
  id: z.int(),
  createdAt: z.iso.datetime(),
  balance: z.number(),
  highestBalance: z.number(),
  highestRealizedBalance: z.number(),
  minimumMll: z.optional(z.number()),
  winPercentage: z.number(),
  winningTrades: z.number(),
  totalTrades: z.int(),
  dailyTrades: z.int(),
  status: zTradingAccountStatus,
  lockoutExpiration: z.optional(z.iso.datetime()),
  lockoutReason: z.optional(z.string()),
  dailyTradeLimit: z.optional(z.int()),
  weeklyTradeLimit: z.optional(z.int()),
  ineligible: z.boolean(),
  startingBalance: z.number(),
  platformAccountId: z.optional(z.string()),
  platformUserName: z.optional(z.string()),
  platformId: zPlatformId,
  tradingCombineId: z.optional(z.int()),
  userId: z.int(),
  isSharing: z.boolean(),
  autoOcoBrackets: z.boolean(),
  name: z.string(),
  nickname: z.optional(z.string()),
  realizedDayPnl: z.number(),
  externalName: z.optional(z.string()),
  maxPositionSize: z.int(),
  drawDownLimit: z.number(),
  dailyLossLimit: z.number(),
  overrideDailyLossLimit: z.optional(z.number()),
  overrideMaxLossLimit: z.optional(z.number()),
  personalDailyLossLimit: z.optional(z.number()),
  personalDailyLossLimitTrailing: z.boolean(),
  pdllTrailingType: zPersonalDailyLossLimitTrailingType,
  personalDailyLossLimitAction: zPersonalDailyAction,
  personalDailyProfitTarget: z.optional(z.number()),
  personalDailyProfitTargetAction: zPersonalDailyAction,
  pdllTrailingStartingBalance: z.optional(z.number()),
  updatedAt: z.iso.datetime(),
  closedAt: z.optional(z.iso.datetime()),
  closeReason: z.optional(z.string()),
  type: zTradingAccountType,
  internalTag: zTradingAccountInternalTag,
  maxMargin: z.optional(z.number()),
  archived: z.boolean(),
  accountTemplateId: z.optional(z.int()),
  bracketAutoApply: z.optional(z.boolean()),
  bracketAmountToRisk: z.optional(z.number()),
  bracketAmountToMake: z.optional(z.number()),
});

export const zRiskSettingsLockout = z.object({
  tradingAccount: zTradingAccount,
  id: z.int(),
  tradingAccountId: z.int(),
  createdAt: z.iso.datetime(),
  expiresAt: z.iso.datetime(),
});

export const zCreateRiskSettingsLockoutResult = z.object({
  message: z.string(),
  success: z.boolean(),
  newExpiresAt: z.optional(z.iso.datetime()),
});

export const zRiskSettingsLockoutModel = z.object({
  id: z.int(),
  tradingAccountId: z.int(),
  createdAt: z.iso.datetime(),
  expiresAt: z.iso.datetime(),
});

/**
 * 0 = Success
 * 1 = Expired
 * 2 = Invalid
 */
export const zSessionValidationResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zUserSessionValidateResponse = z.object({
  token: z.string(),
  sessionId: z.string(),
  result: zSessionValidationResult,
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = TokenNotFound
 * 3 = UnknownError
 */
export const zSsoErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

export const zSsoGenerateResponse = z.object({
  errorCode: zSsoErrorCode,
  errorMessage: z.optional(z.string()),
  token: z.optional(z.string()),
});

export const zSsoGenerateRequest = z.object({
  userName: z.string(),
});

export const zSsoLoginResponse = z.object({
  errorCode: zSsoErrorCode,
  errorMessage: z.optional(z.string()),
  token: z.optional(z.string()),
});

export const zSsoLoginRequest = z.object({
  token: z.string(),
});

export const zProductStatistic = z.object({
  tradeDay: z.iso.datetime(),
  symbolId: z.string(),
  totalTradedContracts: z.int(),
});

export const zDayStatistic = z.object({
  tradeDate: z.iso.datetime(),
  totalPnL: z.number(),
  totalTrades: z.int(),
  winningTrades: z.int(),
  losingTrades: z.int(),
  neutralTrades: z.int(),
  winRate: z.number(),
  totalFees: z.number(),
});

export const zCompleteDayStatistic = zDayStatistic.and(
  z.object({
    tradeDay: z.iso.datetime(),
    balance: z.number(),
    products: z.array(zProductStatistic),
  }),
);

export const zGetMonthlyStatisticsRequest = z.object({
  tradingAccountId: z.int(),
  startTradeDay: z.optional(z.iso.datetime()),
  endTradeDay: z.optional(z.iso.datetime()),
});

export const zGetWeeklyStatisticsRequest = z.object({
  tradingAccountId: z.int(),
  startTradeDay: z.optional(z.iso.datetime()),
  endTradeDay: z.optional(z.iso.datetime()),
});

export const zGetDailyStatisticsRequest = z.object({
  tradingAccountId: z.int(),
  startTradeDay: z.optional(z.iso.datetime()),
  endTradeDay: z.optional(z.iso.datetime()),
});

export const zProfitFactorData = z.object({
  totalProfit: z.number(),
  totalLoss: z.number(),
});

export const zGetLifetimeStatisticsRequest = z.object({
  tradingAccountId: z.int(),
});

export const zTradeSummary = z.object({
  id: z.coerce.bigint(),
  symbolId: z.string(),
  positionSize: z.number(),
  profitAndLoss: z.optional(z.number()),
  fees: z.optional(z.number()),
  entryPrice: z.number(),
  exitPrice: z.optional(z.number()),
  tradeDay: z.iso.datetime(),
  createdAt: z.iso.datetime(),
  enteredAt: z.iso.datetime(),
});

export const zGetTradesForDayRequest = z.object({
  tradingAccountId: z.int(),
  tradeDay: z.iso.datetime(),
});

export const zAverageWinLossData = z.object({
  averageWin: z.number(),
  averageLoss: z.number(),
});

export const zSetAccountSharingRequest = z.object({
  tradingAccountId: z.int(),
  sharing: z.boolean(),
});

export const zStudyTemplateModel = z.object({
  id: z.int(),
  userId: z.int(),
  name: z.string(),
  content: z.string(),
});

export const zRiskSymbolBlockModel = z.object({
  id: z.int(),
  symbolId: z.string(),
  accountId: z.int(),
});

export const zSetRiskSymbolBlocksResult = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zSetRiskSymbolBlocksRequest = z.object({
  accountId: z.int(),
  symbolBlocks: z.array(z.string()),
});

export const zAddRiskSymbolBlockResult = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zAddRiskSymbolBlockRequest = z.object({
  accountId: z.int(),
  symbolId: z.string(),
});

export const zRemoveRiskSymbolBlockResult = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zRemoveRiskSymbolBlockRequest = z.object({
  accountId: z.int(),
  symbolId: z.string(),
});

/**
 * 0 = Success
 * 1 = DurationTooShort
 * 2 = DurationTooLong
 * 3 = InvalidTradingAccount
 * 4 = NoActiveOrdersOrPositions
 * 5 = Error
 */
export const zTradeClockErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
]);

export const zSetTradeClockResponse = z.object({
  errorCode: zTradeClockErrorCode,
  success: z.boolean(),
  message: z.optional(z.string()),
});

export const zSetTradeClockRequest = z.object({
  tradingAccountId: z.int(),
  duration: z.int(),
});

export const zTradeModel = z.object({
  id: z.coerce.bigint(),
  symbolId: z.string(),
  contractId: z.string(),
  accountId: z.int(),
  createdAt: z.iso.datetime(),
  tradeDay: z.iso.datetime(),
  exitedAt: z.optional(z.iso.datetime()),
  entryPrice: z.number(),
  exitPrice: z.optional(z.number()),
  fees: z.number(),
  pnL: z.optional(z.number()),
  positionSize: z.int(),
  voided: z.boolean(),
  tradeDuration: z.optional(z.string()),
  tradeDurationDisplay: z.string(),
  commissions: z.optional(z.number()),
});

export const zTradesInRangeRequest = z.object({
  tradingAccountId: z.int(),
  start: z.optional(z.iso.datetime()),
  end: z.optional(z.iso.datetime()),
});

/**
 * 0 = Long
 * 1 = Short
 */
export const zTradeType = z.union([z.literal(0), z.literal(1)]);

export const zTradeExportModel = z.object({
  id: z.coerce.bigint(),
  contractName: z.string(),
  enteredAt: z.iso.datetime(),
  exitedAt: z.iso.datetime(),
  entryPrice: z.number(),
  exitPrice: z.number(),
  fees: z.number(),
  pnL: z.number(),
  size: z.int(),
  type: zTradeType,
  tradeDay: z.iso.datetime(),
  tradeDuration: z.string(),
  commissions: z.optional(z.number()),
});

export const zUserExportTradeRequest = z.object({
  tradingAccountId: z.int(),
  start: z.iso.datetime(),
  end: z.iso.datetime(),
  timeZone: z.optional(z.string()),
});

export const zSetTradeLimitsResult = z.object({
  success: z.boolean(),
  message: z.string(),
});

export const zTradeLimitsModel = z.object({
  tradingAccountId: z.int(),
  dailyTradeLimit: z.optional(z.int()),
  weeklyTradeLimit: z.optional(z.int()),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = NameTooLong
 * 3 = NameAlreadyUsed
 * 4 = DoesNotOwnAccount
 */
export const zSetAccountNicknameResultCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zSetAccountNicknameRequest = z.object({
  accountId: z.int(),
  nickname: z.optional(z.string()),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = AccountClosed
 * 3 = InvalidDrawDownLimit
 * 4 = AccountIsFollower
 * 5 = InvalidDailyLossLimit
 * 6 = InvalidMaxLossLimit
 * 7 = Exception
 */
export const zTradingAccountResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

export const zPersonalDailyLimitsResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zPersonalDailyLimitsRequest = z.object({
  tradingAccountId: z.int(),
  personalDailyLossLimit: z.optional(z.number()),
  personalDailyProfitTarget: z.optional(z.number()),
  personalDailyLossLimitAction: zPersonalDailyAction,
  personalDailyProfitTargetAction: zPersonalDailyAction,
  personalDailyLossLimitTrailing: z.boolean(),
  pdllTrailingType: zPersonalDailyLossLimitTrailingType,
});

export const zFollowTraderResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zFollowTraderRequest = z.object({
  leaderId: z.int(),
  tradingAccountId: z.int(),
  ratio: z.number(),
});

export const zFollowTraderEntry = z.object({
  tradingAccountId: z.int(),
  tradingAccountName: z.string(),
  leaderAccountId: z.int(),
  leaderAccountName: z.string(),
  ratio: z.number(),
});

/**
 * 0 = Level1
 * 1 = Level2
 */
export const zMarketDataLevel = z.union([z.literal(0), z.literal(1)]);

export const zTradingAccountModelBase = z.object({
  accountName: z.string(),
  nickname: z.optional(z.string()),
  userId: z.int(),
  startingBalance: z.optional(z.number()),
  balance: z.number(),
  status: z.optional(zTradingAccountStatus),
  lockoutExpiration: z.optional(z.iso.datetime()),
  lockoutReason: z.optional(z.string()),
  dailyTradeLimit: z.optional(z.int()),
  weeklyTradeLimit: z.optional(z.int()),
  marketDataLevel: zMarketDataLevel,
  accountId: z.int(),
  winRate: z.number(),
  profitAndLoss: z.optional(z.number()),
  startDate: z.iso.datetime(),
  closedDate: z.optional(z.iso.datetime()),
  dailyLoss: z.optional(z.number()),
  overrideDailyLossLimit: z.optional(z.number()),
  overrideMaxLossLimit: z.optional(z.number()),
  maximumLoss: z.optional(z.number()),
  drawDownLimit: z.number(),
  combineDailyLoss: z.number(),
  maxPositions: z.int(),
  type: zTradingAccountType,
  startOfDayBalance: z.number(),
  combineName: z.string(),
  platformId: zPlatformId,
  platformAccountId: z.optional(z.string()),
  platformUserName: z.optional(z.string()),
  maxMargin: z.optional(z.number()),
  minimumMll: z.optional(z.number()),
  isSharing: z.boolean(),
  availableCash: z.optional(z.number()),
  autoOcoBrackets: z.boolean(),
  bracketAutoApply: z.optional(z.boolean()),
  bracketAmountToRisk: z.optional(z.number()),
  bracketAmountToMake: z.optional(z.number()),
});

export const zTradingAccountModel = zTradingAccountModelBase.and(
  z.object({
    realizedDayPnl: z.optional(z.number()),
    updatedAt: z.iso.datetime(),
    personalDailyLossLimit: z.optional(z.number()),
    personalDailyLossLimitAction: zPersonalDailyAction,
    personalDailyLossLimitTrailing: z.boolean(),
    pdllTrailingType: zPersonalDailyLossLimitTrailingType,
    pdllTrailingBalance: z.optional(z.number()),
    pdllTrailingStartingBalance: z.optional(z.number()),
    personalDailyProfitTarget: z.optional(z.number()),
    personalDailyProfitTargetAction: zPersonalDailyAction,
    totalProfit: z.number(),
    totalLoss: z.number(),
    totalTrades: z.int(),
    dailyTrades: z.int(),
    isFollower: z.boolean(),
    isLeader: z.boolean(),
    openPnl: z.number(),
    highestBalance: z.number(),
    highestUnrealizedBalance: z.number(),
    highestRealizedBalance: z.number(),
    ineligible: z.boolean(),
    templateId: z.optional(z.int()),
    currentDayTrades: z.int(),
    currentWeekTrades: z.int(),
  }),
);

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = AmountToRiskInvalid
 * 3 = AmountToMakeInvalid
 */
export const zSetPositionBracketErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
]);

export const zSetPositionBracketResponse = z.object({
  success: z.boolean(),
  errorCode: zSetPositionBracketErrorCode,
  errorMessage: z.optional(z.string()),
});

/**
 * Represents a request to set position bracket parameters for a specific account.
 */
export const zSetPositionBracketRequest = z.object({
  accountId: z.int(),
  autoApply: z.optional(z.boolean()),
  risk: z.optional(z.number()),
  toMake: z.optional(z.number()),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = AccountClosed
 * 3 = AccountIsFollower
 * 4 = PositionsOpen
 * 5 = OrdersOnBook
 * 6 = Exception
 */
export const zSetAutoOcoBracketsResult = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

/**
 * Response model for setting AutoOcoBrackets on a trading account.
 */
export const zSetAutoOcoBracketsResponse = z.object({
  success: z.boolean(),
  result: zSetAutoOcoBracketsResult,
  errorMessage: z.optional(z.string()),
});

/**
 * Request model for setting AutoOcoBrackets on a trading account.
 */
export const zSetAutoOcoBracketsRequest = z.object({
  tradingAccountId: z.int(),
  autoOcoBrackets: z.boolean(),
});

/**
 * 1 = HighestRealizedPnL
 * 2 = HighestUnrealizedPnL
 */
export const zTradingAccountStateLogType = z.union([
  z.literal(1),
  z.literal(2),
]);

export const zTradingAccountStateLogModel = z.object({
  timestamp: z.iso.datetime(),
  value: z.optional(z.number()),
  type: zTradingAccountStateLogType,
});

export const zTradingAccountStateLogRequest = z.object({
  tradingAccountId: z.int(),
  type: z.optional(zTradingAccountStateLogType),
  startTime: z.optional(z.iso.datetime()),
  endTime: z.optional(z.iso.datetime()),
});

export const zTradingRuleModel = z.object({
  id: zTradingRuleType,
  name: z.string(),
  priority: z.int(),
});

export const zUserContractModel = z.object({
  productId: z.string(),
  productName: z.string(),
  contractId: z.string(),
  contractName: z.string(),
  tickValue: z.number(),
  tickSize: z.number(),
  pointValue: z.number(),
  exchangeFee: z.number(),
  regulatoryFee: z.number(),
  commissionFee: z.number(),
  totalFees: z.number(),
  description: z.string(),
  disabled: z.boolean(),
  decimalPlaces: z.int(),
  priceScale: z.number(),
  minMove: z.number(),
  fractionalPrice: z.boolean(),
  exchange: z.string(),
  minMove2: z.number(),
  isProfessional: z.boolean(),
});

export const zUserModel = z.object({
  userName: z.string(),
  email: z.string(),
  userId: z.int(),
  firstName: z.string(),
  lastName: z.string(),
  hasSignedAgreements: z.boolean(),
  onboardingRequired: z.boolean(),
  onboardingState: zOnboardingState,
  createdAt: z.iso.datetime(),
  roles: z.array(z.string()),
});

/**
 * Represents a response to a request for creating a new user API key.
 */
export const zCreateUserApiKeyResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
  apiKey: z.optional(z.string()),
});

/**
 * Represents a response to a request for revoking an existing user API key.
 */
export const zRevokeUserApiKeyResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

/**
 * Represents a request to revoke an existing user API key.
 */
export const zRevokeUserApiKeyRequest = z.object({
  apiKey: z.string(),
});

export const zUserApiKeyModel = z.object({
  key: z.string(),
  createdAt: z.iso.datetime(),
  lastUsedAt: z.optional(z.iso.datetime()),
});

export const zDashboardLinkResponse = z.object({
  error: z.optional(z.string()),
  url: z.optional(z.string()),
});

export const zUserDataUploadResponse = z.object({
  success: z.boolean(),
  url: z.string(),
  errorMessage: z.string(),
});

export const zNotificationModel = z.object({
  notificationId: z.int(),
  title: z.string(),
  content: z.string(),
  updatedAt: z.iso.datetime(),
});

export const zReadNotificationResponse = z.object({
  success: z.boolean(),
  errorMessage: z.optional(z.string()),
});

export const zReadNotificationRequest = z.object({
  notificationId: z.int(),
});

export const zRoleModel = z.object({
  id: z.int(),
  name: z.string(),
  description: z.string(),
});

export const zUserRoleModel = z.object({
  roleId: z.int(),
  userId: z.int(),
});

export const zUserSettingsModel = z.object({
  risk: z.optional(z.number()),
  toMake: z.optional(z.number()),
  autoCenter: z.optional(z.boolean()),
  showConfirmations: z.optional(z.boolean()),
  autoApply: z.optional(z.boolean()),
  streamerMode: z.optional(z.boolean()),
  soundNotifications: z.optional(z.boolean()),
  custom: z.optional(zJsonDocument),
});

/**
 * 0 = Unspecified
 * 1 = DailyLossLimit
 * 2 = MaximumLossLimit
 * 3 = PersonalDailyLossLimit
 * 4 = PersonalStop
 * 5 = PersonalDailyProfitTarget
 * 6 = Rule
 * 7 = Custom
 * 8 = TrailingPersonalDailyLossLimit
 */
export const zViolationType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

export const zCustomViolationModel = z.object({
  title: z.string(),
  message: z.optional(z.string()),
  extraData: z.optional(z.string()),
});

export const zActiveViolationModel = z.object({
  type: zViolationType,
  triggeredAt: z.iso.datetime(),
  expiresAt: z.optional(z.iso.datetime()),
  duration: zViolationDuration,
  violationBalance: z.number(),
  violationTotalDayPnl: z.number(),
  minimumBalance: z.number(),
  dailyLossLimit: z.number(),
  personalDailyLossLimit: z.optional(z.number()),
  personalDailyProfitTarget: z.optional(z.number()),
  accountTemplateId: z.optional(z.int()),
  ruleId: z.optional(zTradingRuleType),
  customViolation: z.optional(zCustomViolationModel),
  violationMargin: z.optional(z.number()),
  maxMargin: z.optional(z.number()),
});

export const zUserExportRequest2 = zUserExportRequest;

export const zPlaceOrderRequest2 = zPlaceOrderRequest;

export const zGetDailyStatisticsRequest2 = zGetDailyStatisticsRequest;

export const zLoginRequestModel2 = zLoginRequestModel;

export const zUserExportTradeRequest2 = zUserExportTradeRequest;

export const zDrawingTemplateModel2 = zDrawingTemplateModel;

export const zCreate2FaRequest2 = zCreate2FaRequest;

export const zMultiFactorAuthenticationSubmit2FaToken = z.string();

export const zVerify2FaRequest2 = zVerify2FaRequest;

export const zUserSettingsModel2 = zUserSettingsModel;

export const zAccountTemplateGetUserTemplatesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A list of AccountTemplateModel.
 */
export const zAccountTemplateGetUserTemplatesResponse = z.array(
  zAccountTemplateModel,
);

export const zAccountTemplateRuleGetAllAttachedRulesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountTemplateId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * List of rule types (rule IDs) attached to the template
 */
export const zAccountTemplateRuleGetAllAttachedRulesResponse = z.array(
  zAccountTemplateRuleModel,
);

export const zAutoOcoBracketsDeleteData = z.object({
  body: zAutoOcoBracketRemoveRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAutoOcoBracketsDeleteResponse = zAutoOcoBracketRemoveResponse;

export const zAutoOcoBracketsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAutoOcoBracketsGetResponse = z.array(zAutoOcoBracketModel);

export const zAutoOcoBracketsPostData = z.object({
  body: zAutoOcoBracketRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAutoOcoBracketsPostResponse = zAutoOcoBracketResponse;

export const zChartDataDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      client: z.optional(z.string()),
      user: z.optional(z.string()),
      chart: z.optional(z.string()),
    }),
  ),
});

export const zChartDataDeleteResponse = zChartResult;

export const zChartDataGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      client: z.optional(z.string()),
      user: z.optional(z.string()),
      chart: z.optional(z.string()),
    }),
  ),
});

export const zChartDataGetResponse = zChartResult;

export const zChartDataPostData = z.object({
  body: z.optional(
    z.object({
      name: z.optional(z.string()),
      content: z.optional(z.string()),
      symbol: z.optional(z.string()),
      resolution: z.optional(z.string()),
    }),
  ),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      client: z.optional(z.string()),
      user: z.optional(z.string()),
      chart: z.optional(z.string()),
    }),
  ),
});

export const zChartDataPostResponse = zChartResult;

export const zChartsGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zChartsGetAllResponse = z.array(zChartSummaryModel);

export const zChartsRemoveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zChartsSaveChartData = z.object({
  body: zChartModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zChartsSaveChartResponse = z.string();

export const zChartsGetChartData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    chartId: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zChartsGetChartResponse = z.string();

export const zChartTemplatesGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zChartTemplatesGetAllResponse = z.array(z.string());

export const zChartTemplatesRemoveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    templateName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zChartTemplatesSaveChartTemplateData = z.object({
  body: zChartTemplateModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zChartTemplatesSaveChartTemplateResponse = z.int();

export const zChartTemplatesGetChartTemplateData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    templateName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zChartTemplatesGetChartTemplateResponse = z.string();

export const zContractLimitGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zContractLimitGetAllResponse = z.array(zRiskContractLimitModel);

export const zContractLimitSetData = z.object({
  body: zSetRiskContractLimitsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zContractLimitSetResponse = zSetRiskContractLimitsResult;

export const zDrawingTemplatesGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    toolName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesGetAllResponse = z.array(zDrawingTemplateModel);

export const zDrawingTemplatesGetAllNamesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    toolName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesGetAllNamesResponse = z.array(z.string());

export const zDrawingTemplatesRemoveDrawingTemplateData = z.object({
  body: zRemoveDrawingTemplateRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesSaveDrawingTemplateData = z.object({
  body: zDrawingTemplateModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesSaveDrawingTemplateResponse = z.int();

export const zDrawingTemplatesGetDrawingTemplateData = z.object({
  body: zGetDrawingTemplateRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesGetDrawingTemplateResponse = z.string();

export const zDrawingTemplatesGetDrawingTemplateDepracatedData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    toolName: z.string(),
    templateName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesGetDrawingTemplateDepracatedResponse = z.string();

export const zDrawingTemplatesSaveDrawingTemplateDepracatedData = z.object({
  body: zDrawingTemplateModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDrawingTemplatesSaveDrawingTemplateDepracatedResponse = z.int();

export const zDrawingTemplatesRemoveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    toolName: z.string(),
    templateName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zForgotPasswordGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      userName: z.optional(z.string()),
    }),
  ),
});

export const zForgotPasswordGetResponse = zPasswordResetResult;

export const zForgotPasswordPostData = z.object({
  body: zPasswordResetRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zForgotPasswordPostResponse = zPasswordResetResult;

export const zJournalLogUpsertData = z.object({
  body: zJournalLogUpsertRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zJournalLogUpsertResponse2 = zJournalLogUpsertResponse;

export const zJournalLogGetForDayData = z.object({
  body: zGetJournalLogDayRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zJournalLogGetForDayResponse = z.array(zJournalLog);

export const zJournalLogGetForTradeData = z.object({
  body: zGetJournalLogTradeRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zJournalLogGetForTradeResponse = zJournalLog;

export const zJournalLogGetForRangeData = z.object({
  body: zGetJournalLogRangeRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zJournalLogGetForRangeResponse = z.array(zJournalLog);

export const zJournalLogDeleteData = z.object({
  body: zDeleteJournalLogRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zJournalLogDeleteResponse = z.boolean();

export const zLayoutsDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      id: z.optional(z.int()),
    }),
  ),
});

export const zLayoutsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLayoutsGetResponse = z.array(zLayoutModel);

export const zLayoutsPostData = z.object({
  body: zLayoutModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLayoutsPostResponse = z.int();

export const zLineToolsLoadData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    layoutId: z.string(),
    chartId: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zLineToolsLoadResponse = zLineToolsModel;

export const zLineToolsRemoveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zLineToolsSaveLineToolData = z.object({
  body: zLineToolsModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLineToolsSaveLineToolResponse = z.int();

export const zLinkedOrderUnlinkOrdersData = z.object({
  body: zUnlinkOrderUserRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLinkedOrderUnlinkOrdersResponse = zUnlinkOrderUserResponse;

export const zLinkedOrderGetLinkedOrdersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

export const zLinkedOrderGetLinkedOrdersResponse = zGetLinkedOrdersResponse;

export const zLinkedOrderLinkOrdersData = z.object({
  body: zLinkOrderUserRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLinkedOrderLinkOrdersResponse = zLinkOrderUserResponse;

export const zLoginLoginData = z.object({
  body: zLoginRequestModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A model containing the result of the login attempt and the token, if successful.
 */
export const zLoginLoginResponse = zLoginResultModel;

export const zLoginLoginV2Data = z.object({
  body: zLoginRequestModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A model containing the result of the login attempt and the token, if successful.
 */
export const zLoginLoginV2Response = zLoginResultModel;

export const zLoginApiLoginData = z.object({
  body: zApiKeyLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zLoginApiLoginResponse = zLoginResultModel;

export const zMarketClosureGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketClosureGetResponse = z.array(zMarketClosureModel);

export const zMarketStatusGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusGetResponse = zMarketStatusSummary;

export const zMarketStatusGetSummaryData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusGetSummaryResponse = zMarketStatusSummary;

export const zMarketStatusGetMarketsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusGetMarketsResponse = z.array(zMarketStatus);

export const zMarketStatusSetMarketStatusData = z.object({
  body: zSetSingleMarketStatusRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusSetMarketStatusResponse = zSetMarketStatusResponse;

export const zMarketStatusSetAllMarketStatusData = z.object({
  body: zSetManyMarketStatusRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusSetAllMarketStatusResponse =
  zSetManyMarketStatusResponse;

export const zMarketStatusResetMarketStatusData = z.object({
  body: zResetSingleMarketStatusRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusResetMarketStatusResponse = zSetMarketStatusResponse;

export const zMarketStatusResetAllMarketStatusData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMarketStatusResetAllMarketStatusResponse =
  zSetManyMarketStatusResponse;

export const zMarketStatusDebugMarketStatusData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    symbolId: z.string(),
    num: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zMetadataGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMetadataGetResponse = z.array(zSymbolMetadata);

export const zMigrateDataMigrateChartsPartialData = z.object({
  body: zMigratePartialChartsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMigrateDataMigrateChartsPartialResponse = z.array(z.string());

export const zMigrateDataMigrateChartsData = z.object({
  body: zMigrateChartsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMigrateDataMigrateChartsResponse = z.array(z.string());

export const zMultiFactorAuthenticationCreateData = z.object({
  body: zCreate2FaRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationCreateResponse = zCreateMfaErrorCode;

export const zMultiFactorAuthenticationCreateV2Data = z.object({
  body: zCreate2FaRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationCreateV2Response =
  zCreateRecoveryCodesResult;

export const zMultiFactorAuthenticationSubmit2FaData = z.object({
  body: zMultiFactorAuthenticationSubmit2FaToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationSubmit2FaResponse = zSubmit2FaResult;

export const zMultiFactorAuthenticationSubmitMfaData = z.object({
  body: zVerify2FaRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationSubmitMfaResponse = zSubmit2FaResult;

export const zMultiFactorAuthenticationSubmitRecoveryCodeData = z.object({
  body: zMultiFactorAuthenticationSubmit2FaToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationSubmitRecoveryCodeResponse =
  zSubmitRecoveryCodeResult;

export const zMultiFactorAuthenticationRegenerateRecoveryCodesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationRegenerateRecoveryCodesResponse =
  zRegenerateRecoveryCodesResult;

export const zMultiFactorAuthenticationHas2FaData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationHas2FaResponse = z.boolean();

export const zMultiFactorAuthenticationDisable2FaData = z.object({
  body: zMultiFactorAuthenticationSubmit2FaToken,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationDisable2FaResponse =
  zDisable2FaErrorCode;

export const zMultiFactorAuthenticationDisableMfaData = z.object({
  body: zVerify2FaRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationDisableMfaResponse =
  zDisable2FaErrorCode;

export const zMultiFactorAuthenticationAdminDisable2FaData = z.object({
  body: z.int(),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationAdminDisable2FaResponse =
  zDisable2FaErrorCode;

export const zMultiFactorAuthenticationRequestEmailCodeData = z.object({
  body: zRequestEmailCodeModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationRequestEmailCodeResponse =
  zRequestEmailCodeResult;

export const zMultiFactorAuthenticationHasMfaData = z.object({
  body: zHasMfaRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zMultiFactorAuthenticationHasMfaResponse = zHasMfaResult;

export const zOnboardingGetOnboardingDataData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OnboardingDataModel containing user profile fields, OnboardingRequired,
 * OnboardingState, any required agreements, and placeholder subscriptions.
 */
export const zOnboardingGetOnboardingDataResponse = zOnboardingDataModel;

export const zOnboardingRequestEmailAuthCodeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * RequestEmailCodeResponse with the nonce for the email authentication code.
 */
export const zOnboardingRequestEmailAuthCodeResponse =
  zRequestEmailCodeResponse;

export const zOnboardingSetPasswordData = z.object({
  body: zSetPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * SetPasswordResponse with success flag and error code. Returns
 * InvalidStepOrder if the current OnboardingState does not allow this step.
 */
export const zOnboardingSetPasswordResponse = zSetPasswordResponse;

export const zOnboardingSetupMfaData = z.object({
  body: zSetupMfaRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * SetupMfaResponse with success flag, recovery codes on success, and error code.
 * Returns InvalidStepOrder if the current OnboardingState is not MultiFactorAuth.
 */
export const zOnboardingSetupMfaResponse = zSetupMfaResponse;

export const zOnboardingCreateSubscriptionData = z.object({
  body: zCreateSubscriptionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * CreateSubscriptionResponse with success flag and error code. Returns
 * InvalidStepOrder if the current OnboardingState is not Subscription.
 */
export const zOnboardingCreateSubscriptionResponse =
  zCreateSubscriptionResponse;

export const zOnboardingSignAgreementsData = z.object({
  body: zSignAgreementRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * SignAgreementsResponse with success flag and error code. On success, onboarding is
 * finalized, any previous sessions are revoked, a new session is created, and an AuthToken is returned.
 * Returns InvalidStepOrder if the current OnboardingState is not Agreements.
 */
export const zOnboardingSignAgreementsResponse = zSignAgreementsResponse;

export const zOrderCancelAllAccountOrdersData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * A boolean that is true if the operation was successful; otherwise, false.
 */
export const zOrderCancelAllAccountOrdersResponse = z.boolean();

export const zOrderCancelAccountOrderBySymbolIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
    symbolId: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * A boolean value indicating whether an order was cancelled.
 */
export const zOrderCancelAccountOrderBySymbolIdResponse = z.boolean();

export const zOrderCancelAccountOrderByContractIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
    contractId: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * A boolean value indicating whether an order was cancelled.
 */
export const zOrderCancelAccountOrderByContractIdResponse = z.boolean();

export const zOrderPutTrailingOrderDistanceData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    orderId: z.coerce.bigint(),
  }),
  query: z.optional(
    z.object({
      trailingDistance: z.optional(z.int()),
    }),
  ),
});

/**
 * A boolean value indicating whether the operation was successful.
 */
export const zOrderPutTrailingOrderDistanceResponse = z.boolean();

export const zOrderEditOrderData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    orderId: z.coerce.bigint(),
  }),
  query: z.optional(
    z.object({
      limitPrice: z.optional(z.number()),
    }),
  ),
});

/**
 * A boolean value indicating whether the operation was successful.
 */
export const zOrderEditOrderResponse = z.boolean();

export const zOrderCancelAccountOrderByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
    orderId: z.coerce.bigint(),
  }),
  query: z.optional(z.never()),
});

/**
 * A boolean value indicating whether the cancellation was successful.
 */
export const zOrderCancelAccountOrderByIdResponse = z.boolean();

export const zOrderGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
    }),
  ),
});

/**
 * A list of recent orders for the specified account.
 */
export const zOrderGetResponse = z.array(zOrderModel);

export const zOrderPostData = z.object({
  body: zPlaceOrderRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response containing the result of the order placement operation.
 */
export const zOrderPostResponse = zPlaceOrderResponse;

export const zOrderUserExportJsonData = z.object({
  body: zUserExportRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zOrderUserExportJsonResponse = z.array(zOrderExportModel);

export const zOrderUserExportCsvData = z.object({
  body: zUserExportRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zOrderUserExportCsvResponse = z.string();

export const zOrderUpdateStopLossAccountData = z.object({
  body: zUpdateStopLossAccountRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zOrderUpdateStopLossAccountResponse = zUpdateStopLossResponse;

export const zOrderUpdateStopLossData = z.object({
  body: zUpdateStopLossRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zOrderUpdateStopLossResponse = zUpdateStopLossResponse;

export const zOrderPostWithContractData = z.object({
  body: zPlaceOrderRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response containing the result of the order placement operation.
 */
export const zOrderPostWithContractResponse = zPlaceOrderResponse;

export const zPersonalLockoutGetActiveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tradingAccountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zPersonalLockoutGetActiveResponse = z.array(zPersonalLockoutModel);

export const zPersonalLockoutGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

export const zPersonalLockoutGetAllResponse = z.array(zPersonalLockoutModel);

export const zPersonalLockoutAddData = z.object({
  body: z.array(zPersonalLockoutModel),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPersonalLockoutAddResponse = zSetPersonalLockoutResult;

export const zPositionCloseData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
    symbolId: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zPositionCloseByContractData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
    contractId: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zPositionCloseAllData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zPositionPutRiskToMakeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      PositionId: z.optional(z.int()),
      Risk: z.optional(z.number()),
      ToMake: z.optional(z.number()),
    }),
  ),
});

/**
 * A StopLossTakeProfitModel containing the updated stop-loss and take-profit values.
 */
export const zPositionPutRiskToMakeResponse = zStopLossTakeProfitModel;

export const zPositionPutSltpData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      PositionId: z.optional(z.int()),
      StopLoss: z.optional(z.number()),
      TakeProfit: z.optional(z.number()),
      ErrorMessage: z.optional(z.string()),
      CancellationSource: z.optional(
        z.union([z.literal(0), z.literal(1), z.literal(2)]),
      ),
    }),
  ),
});

/**
 * A StopLossTakeProfitModel containing the updated stop-loss and take-profit values.
 */
export const zPositionPutSltpResponse = zUpdateStopLossTakeProfitResult;

export const zPositionReverseData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
      symbol: z.optional(z.string()),
    }),
  ),
});

/**
 * A boolean indicating the success of the operation.
 */
export const zPositionReverseResponse = z.boolean();

export const zPositionReverseWithTimeTypeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
      symbol: z.optional(z.string()),
      timeType: z.optional(z.union([z.literal(0), z.literal(1)])),
    }),
  ),
});

/**
 * A boolean indicating the success of the operation.
 */
export const zPositionReverseWithTimeTypeResponse = z.boolean();

export const zPositionReverseByContractData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
      contractId: z.optional(z.string()),
    }),
  ),
});

export const zPositionReverseByContractResponse = z.boolean();

export const zPositionReverseByContractWithTimeTypeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
      contractId: z.optional(z.string()),
      timeType: z.optional(z.union([z.literal(0), z.literal(1)])),
    }),
  ),
});

/**
 * A boolean indicating the success of the operation.
 */
export const zPositionReverseByContractWithTimeTypeResponse = z.boolean();

export const zPositionGetByTradingAccountData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * A list of PositionModel representing the open positions for the account.
 */
export const zPositionGetByTradingAccountResponse = z.array(zPositionModel);

export const zPositionGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
    }),
  ),
});

/**
 * A list of PositionModel representing the open positions for the account.
 */
export const zPositionGetResponse = z.array(zPositionModel);

export const zPositionGetAllByUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * A list of PositionModel representing the open positions for the current user.
 */
export const zPositionGetAllByUserResponse = z.array(zPositionModel);

export const zRegisterRegisterData = z.object({
  body: zRegisterRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zRegisterRegisterResponse = zRegisterResponse;

export const zRiskSettingsLockoutGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tradingAccountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zRiskSettingsLockoutGetResponse = zRiskSettingsLockout;

export const zRiskSettingsLockoutAddForDayData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

export const zRiskSettingsLockoutAddForDayResponse =
  zCreateRiskSettingsLockoutResult;

export const zRiskSettingsLockoutAddData = z.object({
  body: zRiskSettingsLockoutModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zRiskSettingsLockoutAddResponse = zCreateRiskSettingsLockoutResult;

export const zSessionValidateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zSessionValidateResponse = zUserSessionValidateResponse;

export const zSingleSignOnGenerateData = z.object({
  body: zSsoGenerateRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A model containing the result of the SSO token generation attempt.
 */
export const zSingleSignOnGenerateResponse = zSsoGenerateResponse;

export const zSingleSignOnLoginData = z.object({
  body: zSsoLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A model containing the result of the SSO login attempt and the authentication token, if successful.
 */
export const zSingleSignOnLoginResponse = zSsoLoginResponse;

export const zStatisticsGetMonthlyData = z.object({
  body: zGetMonthlyStatisticsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetMonthlyResponse = z.array(zCompleteDayStatistic);

export const zStatisticsGetWeeklyData = z.object({
  body: zGetWeeklyStatisticsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetWeeklyResponse = z.array(zCompleteDayStatistic);

export const zStatisticsGetDailyData = z.object({
  body: zGetDailyStatisticsRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetDailyResponse = z.array(zCompleteDayStatistic);

export const zStatisticsGetProfitFactorData = z.object({
  body: zGetDailyStatisticsRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetProfitFactorResponse = zProfitFactorData;

export const zStatisticsGetLifetimeStatsData = z.object({
  body: zGetLifetimeStatisticsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetLifetimeStatsResponse = z.array(zDayStatistic);

export const zStatisticsGetDayStatsData = z.object({
  body: zGetDailyStatisticsRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetDayStatsResponse = z.array(zDayStatistic);

export const zStatisticsGetTodayStatsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      accountId: z.optional(z.int()),
    }),
  ),
});

export const zStatisticsGetTodayStatsResponse = z.array(zCompleteDayStatistic);

export const zStatisticsGetTradesForDayData = z.object({
  body: zGetTradesForDayRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetTradesForDayResponse = z.array(zTradeSummary);

export const zStatisticsGetTradesForRangeData = z.object({
  body: zGetDailyStatisticsRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetTradesForRangeResponse = z.array(zTradeSummary);

export const zStatisticsGetWinLossAvgData = z.object({
  body: zGetDailyStatisticsRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsGetWinLossAvgResponse = zAverageWinLossData;

export const zStatisticsSetAccountSharingData = z.object({
  body: zSetAccountSharingRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStatisticsSetAccountSharingResponse = z.string();

export const zStatisticsCheckAccountSharingData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

export const zStatisticsCheckAccountSharingResponse = z.boolean();

export const zStatisticsGetAccountNameData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

export const zStatisticsGetAccountNameResponse = z.string();

export const zStudyTemplatesGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStudyTemplatesGetAllResponse = z.array(z.string());

export const zStudyTemplatesRemoveByNameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    name: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zStudyTemplatesSaveStudyTemplateData = z.object({
  body: zStudyTemplateModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zStudyTemplatesSaveStudyTemplateResponse = z.int();

export const zStudyTemplatesGetStudyTemplateData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    studyTemplateName: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zStudyTemplatesGetStudyTemplateResponse = z.string();

export const zSymbolBlockGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zSymbolBlockGetAllResponse = z.array(zRiskSymbolBlockModel);

export const zSymbolBlockSetData = z.object({
  body: zSetRiskSymbolBlocksRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zSymbolBlockSetResponse = zSetRiskSymbolBlocksResult;

export const zSymbolBlockAddData = z.object({
  body: zAddRiskSymbolBlockRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zSymbolBlockAddResponse = zAddRiskSymbolBlockResult;

export const zSymbolBlockRemoveData = z.object({
  body: zRemoveRiskSymbolBlockRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zSymbolBlockRemoveResponse = zRemoveRiskSymbolBlockResult;

export const zTiltActivateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      refreshCount: z.optional(z.int()),
    }),
  ),
});

export const zTiltActivateWithAccountIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(
    z.object({
      refreshCount: z.optional(z.int()),
    }),
  ),
});

export const zTradeClockSetTradeClockData = z.object({
  body: zSetTradeClockRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradeClockSetTradeClockResponse = zSetTradeClockResponse;

export const zTradeGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * A list of filled trades for the specified account.
 */
export const zTradeGetResponse = z.array(zTradeModel);

export const zTradeGetInRangeData = z.object({
  body: zTradesInRangeRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradeGetInRangeResponse = z.array(zTradeModel);

export const zTradeUserExportJsonData = z.object({
  body: zUserExportTradeRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradeUserExportJsonResponse = z.array(zTradeExportModel);

export const zTradeUserExportCsvData = z.object({
  body: zUserExportTradeRequest2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradeUserExportCsvResponse = z.string();

export const zTradeLimitAddTradeLimitsData = z.object({
  body: zTradeLimitsModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradeLimitAddTradeLimitsResponse = zSetTradeLimitsResult;

export const zTradingAccountGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A list of TradingAccountModel representing the accounts of the current user.
 */
export const zTradingAccountGetResponse = z.array(zTradingAccountModel);

export const zTradingAccountSetAccountNicknameData = z.object({
  body: zSetAccountNicknameRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradingAccountSetAccountNicknameResponse =
  zSetAccountNicknameResultCode;

export const zTradingAccountSetPersonalDailyLossLimitData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    accountId: z.int(),
  }),
  query: z.optional(
    z.object({
      limit: z.optional(z.number()),
    }),
  ),
});

/**
 * A TradingAccountResult representing the result of the operation.
 */
export const zTradingAccountSetPersonalDailyLossLimitResponse =
  zTradingAccountResult;

export const zTradingAccountSetPersonalDailyLimitsData = z.object({
  body: zPersonalDailyLimitsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradingAccountSetPersonalDailyLimitsResponse =
  zPersonalDailyLimitsResponse;

export const zTradingAccountFollowData = z.object({
  body: zFollowTraderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A FollowTraderResponse indicating the success of the operation and any error message.
 */
export const zTradingAccountFollowResponse = zFollowTraderResponse;

export const zTradingAccountUnfollowData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      tradingAccountId: z.optional(z.int()),
    }),
  ),
});

/**
 * A FollowTraderResponse indicating the success or failure of the operation.
 */
export const zTradingAccountUnfollowResponse = zFollowTraderResponse;

export const zTradingAccountClearFollowersData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tradingAccountId: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * A boolean value that indicates whether the operation was successful.
 */
export const zTradingAccountClearFollowersResponse = z.boolean();

export const zTradingAccountGetFollowEntriesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A list of FollowTraderEntry representing the accounts that the current user has for following trades.
 */
export const zTradingAccountGetFollowEntriesResponse =
  z.array(zFollowTraderEntry);

export const zTradingAccountStopTradingData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tradingAccountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zTradingAccountSetPositionBracketsData = z.object({
  body: zSetPositionBracketRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradingAccountSetPositionBracketsResponse =
  zSetPositionBracketResponse;

export const zTradingAccountSetAutoOcoBracketsData = z.object({
  body: zSetAutoOcoBracketsRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response indicating the success of the operation.
 */
export const zTradingAccountSetAutoOcoBracketsResponse =
  zSetAutoOcoBracketsResponse;

export const zTradingAccountStateLogGetTradingAccountStateLogData = z.object({
  body: zTradingAccountStateLogRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradingAccountStateLogGetTradingAccountStateLogResponse = z.array(
  zTradingAccountStateLogModel,
);

export const zTradingRuleGetTradingRulesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zTradingRuleGetTradingRulesResponse = z.array(zTradingRuleModel);

export const zUserAgreementGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserAgreementGetResponse = z.array(zUserAgreementModel);

export const zUserAgreementSignData = z.object({
  body: zSignAgreementRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserAgreementSignResponse = z.array(zUserAgreementModel);

export const zUserAgreementLegacyGetRequiredData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserAgreementLegacyGetRequiredResponse =
  z.array(zUserAgreementModel);

export const zUserAgreementGetRequiredData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserAgreementGetRequiredResponse = z.array(zUserAgreementModel);

export const zUserContractGetAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserContractGetAllResponse = z.array(zUserContractModel);

export const zUserContractGetNonProfessionalData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserContractGetNonProfessionalResponse =
  z.array(zUserContractModel);

export const zUserContractGetProfessionalData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserContractGetProfessionalResponse = z.array(zUserContractModel);

export const zUserGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A UserModel containing the user's details.
 */
export const zUserGetResponse = zUserModel;

export const zUserPutAgreementsCompletedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      userId: z.optional(z.int()),
    }),
  ),
});

/**
 * A boolean indicating whether the operation was successful.
 */
export const zUserPutAgreementsCompletedResponse = z.boolean();

export const zUserGetIntercomHashData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserGetIntercomHashResponse = z.string();

export const zUserCreateApiKeyData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A CreateUserApiKeyResponse indicating the result of the operation.
 */
export const zUserCreateApiKeyResponse = zCreateUserApiKeyResponse;

export const zUserRevokeApiKeyData = z.object({
  body: zRevokeUserApiKeyRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserRevokeApiKeyResponse = zRevokeUserApiKeyResponse;

export const zUserGetApiKeysData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserGetApiKeysResponse = z.array(zUserApiKeyModel);

export const zUserGetDashboardLinkUrlData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserGetDashboardLinkUrlResponse = zDashboardLinkResponse;

export const zUserGetCurrentTimeUtcData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserGetCurrentTimeUtcResponse = z.iso.datetime();

export const zUserDataUploadUploadUserDataData = z.object({
  body: z.optional(
    z.object({
      ContentType: z.optional(z.string()),
      ContentDisposition: z.optional(z.string()),
      Headers: z.optional(z.array(z.unknown())),
      Length: z.optional(z.coerce.bigint()),
      Name: z.optional(z.string()),
      FileName: z.optional(z.string()),
      file: z.string(),
    }),
  ),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserDataUploadUploadUserDataResponse = zUserDataUploadResponse;

export const zUserNotificationGetUnreadNotificationsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserNotificationGetUnreadNotificationsResponse =
  z.array(zNotificationModel);

export const zUserNotificationReadNotificationData = z.object({
  body: zReadNotificationRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserNotificationReadNotificationResponse =
  zReadNotificationResponse;

export const zUserRoleGetAvailableRolesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserRoleGetAvailableRolesResponse = z.array(zRoleModel);

export const zUserRoleGetUserRolesByUserIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zUserRoleGetUserRolesByUserIdResponse = z.array(zUserRoleModel);

export const zUserRoleGetRolesByUserIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zUserRoleGetRolesByUserIdResponse = z.array(zRoleModel);

export const zUserRoleHasUserRoleData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.int(),
    roleId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zUserRoleHasUserRoleResponse = z.boolean();

export const zUserSettingsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserSettingsGetResponse = zUserSettingsModel;

export const zUserSettingsPostData = z.object({
  body: zUserSettingsModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUserSettingsPostV2Data = z.object({
  body: zUserSettingsModel2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zViolationsGetActiveViolationData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tradingAccountId: z.int(),
  }),
  query: z.optional(z.never()),
});

export const zViolationsGetActiveViolationResponse = zActiveViolationModel;
