// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  AccountSearchAccountsData,
  AccountSearchAccountsResponses,
  AuthLoginAppData,
  AuthLoginAppResponses,
  AuthLoginKeyData,
  AuthLoginKeyResponses,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthValidateData,
  AuthValidateResponses,
  ContractAvailableContractsData,
  ContractAvailableContractsResponses,
  ContractSearchContractByIdData,
  ContractSearchContractByIdResponses,
  ContractSearchContractsData,
  ContractSearchContractsResponses,
  HistoryGetBarsData,
  HistoryGetBarsResponses,
  OrderCancelOrderData,
  OrderCancelOrderResponses,
  OrderModifyOrderData,
  OrderModifyOrderResponses,
  OrderPlaceOrderData,
  OrderPlaceOrderResponses,
  OrderSearchOpenOrdersData,
  OrderSearchOpenOrdersResponses,
  OrderSearchOrdersData,
  OrderSearchOrdersResponses,
  PositionCloseContractPositionData,
  PositionCloseContractPositionResponses,
  PositionPartialCloseContractPositionData,
  PositionPartialCloseContractPositionResponses,
  PositionSearchOpenPositionsData,
  PositionSearchOpenPositionsResponses,
  StatusPingData,
  StatusPingResponses,
  TradeSearchHalfTurnTradesData,
  TradeSearchHalfTurnTradesResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Searches for accounts based on the provided request.
 */
export const accountSearchAccounts = <ThrowOnError extends boolean = false>(
  options: Options<AccountSearchAccountsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AccountSearchAccountsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Account/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login as the specified user using the specified application.
 */
export const authLoginApp = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginAppData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthLoginAppResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Auth/loginApp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login as the specified user using the specified API key.
 */
export const authLoginKey = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginKeyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthLoginKeyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Auth/loginKey",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Logs out the current authenticated user.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthLogoutResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Auth/logout",
    ...options,
  });
};

/**
 * Validates the current user's session.
 */
export const authValidate = <ThrowOnError extends boolean = false>(
  options?: Options<AuthValidateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthValidateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Auth/validate",
    ...options,
  });
};

/**
 * Searches for contracts based on the provided search criteria.
 */
export const contractSearchContracts = <ThrowOnError extends boolean = false>(
  options: Options<ContractSearchContractsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContractSearchContractsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Contract/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Searches for a contract by its ID.
 */
export const contractSearchContractById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContractSearchContractByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContractSearchContractByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Contract/searchById",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Lists available contracts based on the provided request parameters.
 */
export const contractAvailableContracts = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ContractAvailableContractsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContractAvailableContractsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Contract/available",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Retrieves historical bars based on the specified request parameters.
 */
export const historyGetBars = <ThrowOnError extends boolean = false>(
  options: Options<HistoryGetBarsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    HistoryGetBarsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/History/retrieveBars",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Searches for orders based on the provided request.
 */
export const orderSearchOrders = <ThrowOnError extends boolean = false>(
  options: Options<OrderSearchOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderSearchOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Order/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Searches for open (working/active) orders based on the provided request.
 */
export const orderSearchOpenOrders = <ThrowOnError extends boolean = false>(
  options: Options<OrderSearchOpenOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderSearchOpenOrdersResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Order/searchOpen",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Places a new order based on the provided request.
 */
export const orderPlaceOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderPlaceOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderPlaceOrderResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Order/place",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Cancels an existing order based on the provided request.
 */
export const orderCancelOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderCancelOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderCancelOrderResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Order/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Modifies an existing order based on the provided request.
 */
export const orderModifyOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderModifyOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    OrderModifyOrderResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Order/modify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Searches for open positions based on the provided request.
 */
export const positionSearchOpenPositions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PositionSearchOpenPositionsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PositionSearchOpenPositionsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Position/searchOpen",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Closes a contract position based on the provided request.
 */
export const positionCloseContractPosition = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PositionCloseContractPositionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PositionCloseContractPositionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Position/closeContract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Partially closes a contract position based on the provided request.
 */
export const positionPartialCloseContractPosition = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PositionPartialCloseContractPositionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PositionPartialCloseContractPositionResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Position/partialCloseContract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Handles the ping request to check the status of the API.
 */
export const statusPing = <ThrowOnError extends boolean = false>(
  options?: Options<StatusPingData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StatusPingResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Status/ping",
    ...options,
  });
};

/**
 * Searches for half-turn trades based on the provided request parameters.
 */
export const tradeSearchHalfTurnTrades = <ThrowOnError extends boolean = false>(
  options: Options<TradeSearchHalfTurnTradesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    TradeSearchHalfTurnTradesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/Trade/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
