// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.topstepx.com" | (string & {});
};

export type SearchAccountResponse = {
  success: boolean;
  errorCode: SearchAccountErrorCode;
  errorMessage?: string;
  accounts?: Array<TradingAccountModel>;
};

/**
 * 0 = Success
 */
export type SearchAccountErrorCode = 0;

export type TradingAccountModel = {
  id: number;
  name: string;
  balance: number;
  canTrade: boolean;
  isVisible: boolean;
  simulated: boolean;
};

export type SearchAccountRequest = {
  onlyActiveAccounts: boolean;
};

export type LoginResponse = {
  success: boolean;
  errorCode: LoginErrorCode;
  errorMessage?: string;
  token?: string;
};

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = PasswordVerificationFailed
 * 3 = InvalidCredentials
 * 4 = AppNotFound
 * 5 = AppVerificationFailed
 * 6 = InvalidDevice
 * 7 = AgreementsNotSigned
 * 8 = UnknownError
 * 9 = ApiSubscriptionNotFound
 * 10 = ApiKeyAuthenticationDisabled
 */
export type LoginErrorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export type LoginAppRequest = {
  userName: string;
  password: string;
  deviceId: string;
  appId: string;
  verifyKey: string;
};

export type LoginApiKeyRequest = {
  userName: string;
  apiKey: string;
};

export type LogoutResponse = {
  success: boolean;
  errorCode: LogoutErrorCode;
  errorMessage?: string;
};

/**
 * 0 = Success
 * 1 = InvalidSession
 * 2 = UnknownError
 */
export type LogoutErrorCode = 0 | 1 | 2;

export type ValidateResponse = {
  success: boolean;
  errorCode: ValidateErrorCode;
  errorMessage?: string;
  newToken?: string;
};

/**
 * 0 = Success
 * 1 = InvalidSession
 * 2 = SessionNotFound
 * 3 = ExpiredToken
 * 4 = UnknownError
 */
export type ValidateErrorCode = 0 | 1 | 2 | 3 | 4;

export type SearchContractResponse = {
  success: boolean;
  errorCode: SearchContractErrorCode;
  errorMessage?: string;
  contracts?: Array<ContractModel>;
};

/**
 * 0 = Success
 */
export type SearchContractErrorCode = 0;

export type ContractModel = {
  id: string;
  name: string;
  description: string;
  tickSize: number;
  tickValue: number;
  activeContract: boolean;
  symbolId: string;
};

export type SearchContractRequest = {
  searchText?: string;
  live: boolean;
};

export type SearchContractByIdResponse = {
  success: boolean;
  errorCode: SearchContractByIdErrorCode;
  errorMessage?: string;
  contract?: ContractModel;
};

/**
 * 0 = Success
 * 1 = ContractNotFound
 */
export type SearchContractByIdErrorCode = 0 | 1;

export type SearchContractByIdRequest = {
  contractId: string;
};

export type ListAvailableContractResponse = {
  success: boolean;
  errorCode: ListAvailableContractErrorCode;
  errorMessage?: string;
  contracts?: Array<ContractModel>;
};

/**
 * 0 = Success
 */
export type ListAvailableContractErrorCode = 0;

export type ListAvailableContractRequest = {
  live: boolean;
};

export type RetrieveBarResponse = {
  success: boolean;
  errorCode: RetrieveBarErrorCode;
  errorMessage?: string;
  bars?: Array<AggregateBarModel>;
};

/**
 * 0 = Success
 * 1 = ContractNotFound
 * 2 = UnitInvalid
 * 3 = UnitNumberInvalid
 * 4 = LimitInvalid
 */
export type RetrieveBarErrorCode = 0 | 1 | 2 | 3 | 4;

export type AggregateBarModel = {
  t: string;
  o: number;
  h: number;
  l: number;
  c: number;
  v: number;
};

export type RetrieveBarRequest = {
  contractId: string;
  live: boolean;
  startTime: string;
  endTime: string;
  unit: AggregateBarUnit;
  unitNumber: number;
  limit: number;
  includePartialBar: boolean;
};

/**
 * 0 = Unspecified
 * 1 = Second
 * 2 = Minute
 * 3 = Hour
 * 4 = Day
 * 5 = Week
 * 6 = Month
 */
export type AggregateBarUnit = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type SearchOrderResponse = {
  success: boolean;
  errorCode: SearchOrderErrorCode;
  errorMessage?: string;
  orders?: Array<OrderModel>;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export type SearchOrderErrorCode = 0 | 1;

export type OrderModel = {
  id: number;
  accountId: number;
  contractId: string;
  symbolId: string;
  creationTimestamp: string;
  updateTimestamp?: string;
  status: OrderStatus;
  type: OrderType;
  side: OrderSide;
  size: number;
  limitPrice?: number;
  stopPrice?: number;
  fillVolume: number;
  filledPrice?: number;
  customTag?: string;
};

/**
 * 0 = None
 * 1 = Open
 * 2 = Filled
 * 3 = Cancelled
 * 4 = Expired
 * 5 = Rejected
 * 6 = Pending
 * 7 = PendingCancellation
 * 8 = Suspended
 */
export type OrderStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * 0 = Unknown
 * 1 = Limit
 * 2 = Market
 * 3 = StopLimit
 * 4 = Stop
 * 5 = TrailingStop
 * 6 = JoinBid
 * 7 = JoinAsk
 */
export type OrderType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

/**
 * 0 = Bid
 * 1 = Ask
 */
export type OrderSide = 0 | 1;

export type SearchOrderRequest = {
  accountId: number;
  startTimestamp: string;
  endTimestamp?: string;
};

export type SearchOpenOrderRequest = {
  accountId: number;
};

export type PlaceOrderResponse = {
  success: boolean;
  errorCode: PlaceOrderErrorCode;
  errorMessage?: string;
  orderId?: number;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderRejected
 * 3 = InsufficientFunds
 * 4 = AccountViolation
 * 5 = OutsideTradingHours
 * 6 = OrderPending
 * 7 = UnknownError
 * 8 = ContractNotFound
 * 9 = ContractNotActive
 * 10 = AccountRejected
 */
export type PlaceOrderErrorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export type PlaceOrderRequest = {
  accountId: number;
  contractId: string;
  type: OrderType;
  side: OrderSide;
  size: number;
  limitPrice?: number;
  stopPrice?: number;
  trailPrice?: number;
  customTag?: string;
  stopLossBracket?: PlaceOrderBracket;
  takeProfitBracket?: PlaceOrderBracket;
};

export type PlaceOrderBracket = {
  ticks: number;
  type: OrderType;
};

export type CancelOrderResponse = {
  success: boolean;
  errorCode: CancelOrderErrorCode;
  errorMessage?: string;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderNotFound
 * 3 = Rejected
 * 4 = Pending
 * 5 = UnknownError
 * 6 = AccountRejected
 */
export type CancelOrderErrorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type CancelOrderRequest = {
  accountId: number;
  orderId: number;
};

export type ModifyOrderResponse = {
  success: boolean;
  errorCode: ModifyOrderErrorCode;
  errorMessage?: string;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderNotFound
 * 3 = Rejected
 * 4 = Pending
 * 5 = UnknownError
 * 6 = AccountRejected
 * 7 = ContractNotFound
 */
export type ModifyOrderErrorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export type ModifyOrderRequest = {
  accountId: number;
  orderId: number;
  size?: number;
  limitPrice?: number;
  stopPrice?: number;
  trailPrice?: number;
};

export type SearchPositionResponse = {
  success: boolean;
  errorCode: SearchPositionErrorCode;
  errorMessage?: string;
  positions?: Array<PositionModel>;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export type SearchPositionErrorCode = 0 | 1;

export type PositionModel = {
  id: number;
  accountId: number;
  contractId: string;
  creationTimestamp: string;
  type: PositionType;
  size: number;
  averagePrice: number;
};

/**
 * 0 = Undefined
 * 1 = Long
 * 2 = Short
 */
export type PositionType = 0 | 1 | 2;

export type SearchPositionRequest = {
  accountId: number;
};

export type ClosePositionResponse = {
  success: boolean;
  errorCode: ClosePositionErrorCode;
  errorMessage?: string;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = PositionNotFound
 * 3 = ContractNotFound
 * 4 = ContractNotActive
 * 5 = OrderRejected
 * 6 = OrderPending
 * 7 = UnknownError
 * 8 = AccountRejected
 */
export type ClosePositionErrorCode = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type CloseContractPositionRequest = {
  accountId: number;
  contractId: string;
};

export type PartialClosePositionResponse = {
  success: boolean;
  errorCode: PartialClosePositionErrorCode;
  errorMessage?: string;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = PositionNotFound
 * 3 = ContractNotFound
 * 4 = ContractNotActive
 * 5 = InvalidCloseSize
 * 6 = OrderRejected
 * 7 = OrderPending
 * 8 = UnknownError
 * 9 = AccountRejected
 */
export type PartialClosePositionErrorCode =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9;

export type PartialCloseContractPositionRequest = {
  accountId: number;
  contractId: string;
  size: number;
};

export type SearchHalfTradeResponse = {
  success: boolean;
  errorCode: SearchTradeErrorCode;
  errorMessage?: string;
  trades?: Array<HalfTradeModel>;
};

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export type SearchTradeErrorCode = 0 | 1;

export type HalfTradeModel = {
  id: number;
  accountId: number;
  contractId: string;
  creationTimestamp: string;
  price: number;
  profitAndLoss?: number;
  fees: number;
  side: OrderSide;
  size: number;
  voided: boolean;
  orderId: number;
};

export type SearchTradeRequest = {
  accountId: number;
  startTimestamp?: string;
  endTimestamp?: string;
};

export type AccountSearchAccountsData = {
  /**
   * The request containing search criteria.
   */
  body: SearchAccountRequest;
  path?: never;
  query?: never;
  url: "/api/Account/search";
};

export type AccountSearchAccountsResponses = {
  /**
   * The search account response.
   */
  200: SearchAccountResponse;
};

export type AccountSearchAccountsResponse =
  AccountSearchAccountsResponses[keyof AccountSearchAccountsResponses];

export type AuthLoginAppData = {
  /**
   * The login request.
   */
  body: LoginAppRequest;
  path?: never;
  query?: never;
  url: "/api/Auth/loginApp";
};

export type AuthLoginAppResponses = {
  200: LoginResponse;
};

export type AuthLoginAppResponse =
  AuthLoginAppResponses[keyof AuthLoginAppResponses];

export type AuthLoginKeyData = {
  /**
   * The login request.
   */
  body: LoginApiKeyRequest;
  path?: never;
  query?: never;
  url: "/api/Auth/loginKey";
};

export type AuthLoginKeyResponses = {
  200: LoginResponse;
};

export type AuthLoginKeyResponse =
  AuthLoginKeyResponses[keyof AuthLoginKeyResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Auth/logout";
};

export type AuthLogoutResponses = {
  200: LogoutResponse;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthValidateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Auth/validate";
};

export type AuthValidateResponses = {
  200: ValidateResponse;
};

export type AuthValidateResponse =
  AuthValidateResponses[keyof AuthValidateResponses];

export type ContractSearchContractsData = {
  /**
   * The search criteria for finding contracts.
   */
  body: SearchContractRequest;
  path?: never;
  query?: never;
  url: "/api/Contract/search";
};

export type ContractSearchContractsResponses = {
  /**
   * A response containing the search results, including any matching contracts.
   */
  200: SearchContractResponse;
};

export type ContractSearchContractsResponse =
  ContractSearchContractsResponses[keyof ContractSearchContractsResponses];

export type ContractSearchContractByIdData = {
  /**
   * The request containing the contract ID.
   */
  body: SearchContractByIdRequest;
  path?: never;
  query?: never;
  url: "/api/Contract/searchById";
};

export type ContractSearchContractByIdResponses = {
  /**
   * A response containing the search result, including the matching contract if found.
   */
  200: SearchContractByIdResponse;
};

export type ContractSearchContractByIdResponse =
  ContractSearchContractByIdResponses[keyof ContractSearchContractByIdResponses];

export type ContractAvailableContractsData = {
  /**
   * The listing criteria for available contracts.
   */
  body: ListAvailableContractRequest;
  path?: never;
  query?: never;
  url: "/api/Contract/available";
};

export type ContractAvailableContractsResponses = {
  /**
   * A response containing the list of available contracts.
   */
  200: ListAvailableContractResponse;
};

export type ContractAvailableContractsResponse =
  ContractAvailableContractsResponses[keyof ContractAvailableContractsResponses];

export type HistoryGetBarsData = {
  /**
   * The request containing parameters for retrieving historical bars.
   */
  body: RetrieveBarRequest;
  path?: never;
  query?: never;
  url: "/api/History/retrieveBars";
};

export type HistoryGetBarsResponses = {
  /**
   * The response with the retrieved bars.
   */
  200: RetrieveBarResponse;
};

export type HistoryGetBarsResponse =
  HistoryGetBarsResponses[keyof HistoryGetBarsResponses];

export type OrderSearchOrdersData = {
  /**
   * A request containing search criteria.
   */
  body: SearchOrderRequest;
  path?: never;
  query?: never;
  url: "/api/Order/search";
};

export type OrderSearchOrdersResponses = {
  /**
   * A response with search results.
   */
  200: SearchOrderResponse;
};

export type OrderSearchOrdersResponse =
  OrderSearchOrdersResponses[keyof OrderSearchOrdersResponses];

export type OrderSearchOpenOrdersData = {
  /**
   * A request containing search criteria.
   */
  body: SearchOpenOrderRequest;
  path?: never;
  query?: never;
  url: "/api/Order/searchOpen";
};

export type OrderSearchOpenOrdersResponses = {
  /**
   * A response with search results.
   */
  200: SearchOrderResponse;
};

export type OrderSearchOpenOrdersResponse =
  OrderSearchOpenOrdersResponses[keyof OrderSearchOpenOrdersResponses];

export type OrderPlaceOrderData = {
  /**
   * A request containing order details.
   */
  body: PlaceOrderRequest;
  path?: never;
  query?: never;
  url: "/api/Order/place";
};

export type OrderPlaceOrderResponses = {
  /**
   * A response with order placement details.
   */
  200: PlaceOrderResponse;
};

export type OrderPlaceOrderResponse =
  OrderPlaceOrderResponses[keyof OrderPlaceOrderResponses];

export type OrderCancelOrderData = {
  /**
   * A request containing order cancellation details.
   */
  body: CancelOrderRequest;
  path?: never;
  query?: never;
  url: "/api/Order/cancel";
};

export type OrderCancelOrderResponses = {
  /**
   * A response with order cancellation details.
   */
  200: CancelOrderResponse;
};

export type OrderCancelOrderResponse =
  OrderCancelOrderResponses[keyof OrderCancelOrderResponses];

export type OrderModifyOrderData = {
  /**
   * A request containing order modification details.
   */
  body: ModifyOrderRequest;
  path?: never;
  query?: never;
  url: "/api/Order/modify";
};

export type OrderModifyOrderResponses = {
  /**
   * A response with order modification details.
   */
  200: ModifyOrderResponse;
};

export type OrderModifyOrderResponse =
  OrderModifyOrderResponses[keyof OrderModifyOrderResponses];

export type PositionSearchOpenPositionsData = {
  /**
   * A request containing search criteria.
   */
  body: SearchPositionRequest;
  path?: never;
  query?: never;
  url: "/api/Position/searchOpen";
};

export type PositionSearchOpenPositionsResponses = {
  /**
   * A response with search results.
   */
  200: SearchPositionResponse;
};

export type PositionSearchOpenPositionsResponse =
  PositionSearchOpenPositionsResponses[keyof PositionSearchOpenPositionsResponses];

export type PositionCloseContractPositionData = {
  /**
   * A request containing the account ID and contract ID to close.
   */
  body: CloseContractPositionRequest;
  path?: never;
  query?: never;
  url: "/api/Position/closeContract";
};

export type PositionCloseContractPositionResponses = {
  /**
   * A response indicating the success or failure of the close operation.
   */
  200: ClosePositionResponse;
};

export type PositionCloseContractPositionResponse =
  PositionCloseContractPositionResponses[keyof PositionCloseContractPositionResponses];

export type PositionPartialCloseContractPositionData = {
  /**
   * A request containing the account ID, contract ID, and size to close.
   */
  body: PartialCloseContractPositionRequest;
  path?: never;
  query?: never;
  url: "/api/Position/partialCloseContract";
};

export type PositionPartialCloseContractPositionResponses = {
  /**
   * A response indicating the success or failure of the partial close operation.
   */
  200: PartialClosePositionResponse;
};

export type PositionPartialCloseContractPositionResponse =
  PositionPartialCloseContractPositionResponses[keyof PositionPartialCloseContractPositionResponses];

export type StatusPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Status/ping";
};

export type StatusPingResponses = {
  /**
   * Returns a "pong" to indicate the API is responsive.
   */
  200: string;
};

export type StatusPingResponse = StatusPingResponses[keyof StatusPingResponses];

export type TradeSearchHalfTurnTradesData = {
  /**
   * A request containing search criteria.
   */
  body: SearchTradeRequest;
  path?: never;
  query?: never;
  url: "/api/Trade/search";
};

export type TradeSearchHalfTurnTradesResponses = {
  /**
   * A response with the search results.
   */
  200: SearchHalfTradeResponse;
};

export type TradeSearchHalfTurnTradesResponse =
  TradeSearchHalfTurnTradesResponses[keyof TradeSearchHalfTurnTradesResponses];
