// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * 0 = Success
 */
export const zSearchAccountErrorCode = z.literal(0);

export const zTradingAccountModel = z.object({
  id: z.int(),
  name: z.string(),
  balance: z.number(),
  canTrade: z.boolean(),
  isVisible: z.boolean(),
  simulated: z.boolean(),
});

export const zSearchAccountResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchAccountErrorCode,
  errorMessage: z.optional(z.string()),
  accounts: z.optional(z.array(zTradingAccountModel)),
});

export const zSearchAccountRequest = z.object({
  onlyActiveAccounts: z.boolean(),
});

/**
 * 0 = Success
 * 1 = UserNotFound
 * 2 = PasswordVerificationFailed
 * 3 = InvalidCredentials
 * 4 = AppNotFound
 * 5 = AppVerificationFailed
 * 6 = InvalidDevice
 * 7 = AgreementsNotSigned
 * 8 = UnknownError
 * 9 = ApiSubscriptionNotFound
 * 10 = ApiKeyAuthenticationDisabled
 */
export const zLoginErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
  z.literal(9),
  z.literal(10),
]);

export const zLoginResponse = z.object({
  success: z.boolean(),
  errorCode: zLoginErrorCode,
  errorMessage: z.optional(z.string()),
  token: z.optional(z.string()),
});

export const zLoginAppRequest = z.object({
  userName: z.string(),
  password: z.string(),
  deviceId: z.string(),
  appId: z.string(),
  verifyKey: z.string(),
});

export const zLoginApiKeyRequest = z.object({
  userName: z.string(),
  apiKey: z.string(),
});

/**
 * 0 = Success
 * 1 = InvalidSession
 * 2 = UnknownError
 */
export const zLogoutErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zLogoutResponse = z.object({
  success: z.boolean(),
  errorCode: zLogoutErrorCode,
  errorMessage: z.optional(z.string()),
});

/**
 * 0 = Success
 * 1 = InvalidSession
 * 2 = SessionNotFound
 * 3 = ExpiredToken
 * 4 = UnknownError
 */
export const zValidateErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zValidateResponse = z.object({
  success: z.boolean(),
  errorCode: zValidateErrorCode,
  errorMessage: z.optional(z.string()),
  newToken: z.optional(z.string()),
});

/**
 * 0 = Success
 */
export const zSearchContractErrorCode = z.literal(0);

export const zContractModel = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  tickSize: z.number(),
  tickValue: z.number(),
  activeContract: z.boolean(),
  symbolId: z.string(),
});

export const zSearchContractResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchContractErrorCode,
  errorMessage: z.optional(z.string()),
  contracts: z.optional(z.array(zContractModel)),
});

export const zSearchContractRequest = z.object({
  searchText: z.optional(z.string()),
  live: z.boolean(),
});

/**
 * 0 = Success
 * 1 = ContractNotFound
 */
export const zSearchContractByIdErrorCode = z.union([
  z.literal(0),
  z.literal(1),
]);

export const zSearchContractByIdResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchContractByIdErrorCode,
  errorMessage: z.optional(z.string()),
  contract: z.optional(zContractModel),
});

export const zSearchContractByIdRequest = z.object({
  contractId: z.string(),
});

/**
 * 0 = Success
 */
export const zListAvailableContractErrorCode = z.literal(0);

export const zListAvailableContractResponse = z.object({
  success: z.boolean(),
  errorCode: zListAvailableContractErrorCode,
  errorMessage: z.optional(z.string()),
  contracts: z.optional(z.array(zContractModel)),
});

export const zListAvailableContractRequest = z.object({
  live: z.boolean(),
});

/**
 * 0 = Success
 * 1 = ContractNotFound
 * 2 = UnitInvalid
 * 3 = UnitNumberInvalid
 * 4 = LimitInvalid
 */
export const zRetrieveBarErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);

export const zAggregateBarModel = z.object({
  t: z.iso.datetime(),
  o: z.number(),
  h: z.number(),
  l: z.number(),
  c: z.number(),
  v: z.coerce.bigint(),
});

export const zRetrieveBarResponse = z.object({
  success: z.boolean(),
  errorCode: zRetrieveBarErrorCode,
  errorMessage: z.optional(z.string()),
  bars: z.optional(z.array(zAggregateBarModel)),
});

/**
 * 0 = Unspecified
 * 1 = Second
 * 2 = Minute
 * 3 = Hour
 * 4 = Day
 * 5 = Week
 * 6 = Month
 */
export const zAggregateBarUnit = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

export const zRetrieveBarRequest = z.object({
  contractId: z.string(),
  live: z.boolean(),
  startTime: z.iso.datetime(),
  endTime: z.iso.datetime(),
  unit: zAggregateBarUnit,
  unitNumber: z.int(),
  limit: z.int(),
  includePartialBar: z.boolean(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export const zSearchOrderErrorCode = z.union([z.literal(0), z.literal(1)]);

/**
 * 0 = None
 * 1 = Open
 * 2 = Filled
 * 3 = Cancelled
 * 4 = Expired
 * 5 = Rejected
 * 6 = Pending
 * 7 = PendingCancellation
 * 8 = Suspended
 */
export const zOrderStatus = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

/**
 * 0 = Unknown
 * 1 = Limit
 * 2 = Market
 * 3 = StopLimit
 * 4 = Stop
 * 5 = TrailingStop
 * 6 = JoinBid
 * 7 = JoinAsk
 */
export const zOrderType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

/**
 * 0 = Bid
 * 1 = Ask
 */
export const zOrderSide = z.union([z.literal(0), z.literal(1)]);

export const zOrderModel = z.object({
  id: z.coerce.bigint(),
  accountId: z.int(),
  contractId: z.string(),
  symbolId: z.string(),
  creationTimestamp: z.iso.datetime(),
  updateTimestamp: z.optional(z.iso.datetime()),
  status: zOrderStatus,
  type: zOrderType,
  side: zOrderSide,
  size: z.int(),
  limitPrice: z.optional(z.number()),
  stopPrice: z.optional(z.number()),
  fillVolume: z.int(),
  filledPrice: z.optional(z.number()),
  customTag: z.optional(z.string()),
});

export const zSearchOrderResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchOrderErrorCode,
  errorMessage: z.optional(z.string()),
  orders: z.optional(z.array(zOrderModel)),
});

export const zSearchOrderRequest = z.object({
  accountId: z.int(),
  startTimestamp: z.iso.datetime(),
  endTimestamp: z.optional(z.iso.datetime()),
});

export const zSearchOpenOrderRequest = z.object({
  accountId: z.int(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderRejected
 * 3 = InsufficientFunds
 * 4 = AccountViolation
 * 5 = OutsideTradingHours
 * 6 = OrderPending
 * 7 = UnknownError
 * 8 = ContractNotFound
 * 9 = ContractNotActive
 * 10 = AccountRejected
 */
export const zPlaceOrderErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
  z.literal(9),
  z.literal(10),
]);

export const zPlaceOrderResponse = z.object({
  success: z.boolean(),
  errorCode: zPlaceOrderErrorCode,
  errorMessage: z.optional(z.string()),
  orderId: z.optional(z.coerce.bigint()),
});

export const zPlaceOrderBracket = z.object({
  ticks: z.int(),
  type: zOrderType,
});

export const zPlaceOrderRequest = z.object({
  accountId: z.int(),
  contractId: z.string(),
  type: zOrderType,
  side: zOrderSide,
  size: z.int(),
  limitPrice: z.optional(z.number()),
  stopPrice: z.optional(z.number()),
  trailPrice: z.optional(z.number()),
  customTag: z.optional(z.string()),
  stopLossBracket: z.optional(zPlaceOrderBracket),
  takeProfitBracket: z.optional(zPlaceOrderBracket),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderNotFound
 * 3 = Rejected
 * 4 = Pending
 * 5 = UnknownError
 * 6 = AccountRejected
 */
export const zCancelOrderErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
]);

export const zCancelOrderResponse = z.object({
  success: z.boolean(),
  errorCode: zCancelOrderErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zCancelOrderRequest = z.object({
  accountId: z.int(),
  orderId: z.coerce.bigint(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = OrderNotFound
 * 3 = Rejected
 * 4 = Pending
 * 5 = UnknownError
 * 6 = AccountRejected
 * 7 = ContractNotFound
 */
export const zModifyOrderErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
]);

export const zModifyOrderResponse = z.object({
  success: z.boolean(),
  errorCode: zModifyOrderErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zModifyOrderRequest = z.object({
  accountId: z.int(),
  orderId: z.coerce.bigint(),
  size: z.optional(z.int()),
  limitPrice: z.optional(z.number()),
  stopPrice: z.optional(z.number()),
  trailPrice: z.optional(z.number()),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export const zSearchPositionErrorCode = z.union([z.literal(0), z.literal(1)]);

/**
 * 0 = Undefined
 * 1 = Long
 * 2 = Short
 */
export const zPositionType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
]);

export const zPositionModel = z.object({
  id: z.int(),
  accountId: z.int(),
  contractId: z.string(),
  creationTimestamp: z.iso.datetime(),
  type: zPositionType,
  size: z.int(),
  averagePrice: z.number(),
});

export const zSearchPositionResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchPositionErrorCode,
  errorMessage: z.optional(z.string()),
  positions: z.optional(z.array(zPositionModel)),
});

export const zSearchPositionRequest = z.object({
  accountId: z.int(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = PositionNotFound
 * 3 = ContractNotFound
 * 4 = ContractNotActive
 * 5 = OrderRejected
 * 6 = OrderPending
 * 7 = UnknownError
 * 8 = AccountRejected
 */
export const zClosePositionErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
]);

export const zClosePositionResponse = z.object({
  success: z.boolean(),
  errorCode: zClosePositionErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zCloseContractPositionRequest = z.object({
  accountId: z.int(),
  contractId: z.string(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 * 2 = PositionNotFound
 * 3 = ContractNotFound
 * 4 = ContractNotActive
 * 5 = InvalidCloseSize
 * 6 = OrderRejected
 * 7 = OrderPending
 * 8 = UnknownError
 * 9 = AccountRejected
 */
export const zPartialClosePositionErrorCode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
  z.literal(9),
]);

export const zPartialClosePositionResponse = z.object({
  success: z.boolean(),
  errorCode: zPartialClosePositionErrorCode,
  errorMessage: z.optional(z.string()),
});

export const zPartialCloseContractPositionRequest = z.object({
  accountId: z.int(),
  contractId: z.string(),
  size: z.int(),
});

/**
 * 0 = Success
 * 1 = AccountNotFound
 */
export const zSearchTradeErrorCode = z.union([z.literal(0), z.literal(1)]);

export const zHalfTradeModel = z.object({
  id: z.coerce.bigint(),
  accountId: z.int(),
  contractId: z.string(),
  creationTimestamp: z.iso.datetime(),
  price: z.number(),
  profitAndLoss: z.optional(z.number()),
  fees: z.number(),
  side: zOrderSide,
  size: z.int(),
  voided: z.boolean(),
  orderId: z.coerce.bigint(),
});

export const zSearchHalfTradeResponse = z.object({
  success: z.boolean(),
  errorCode: zSearchTradeErrorCode,
  errorMessage: z.optional(z.string()),
  trades: z.optional(z.array(zHalfTradeModel)),
});

export const zSearchTradeRequest = z.object({
  accountId: z.int(),
  startTimestamp: z.optional(z.iso.datetime()),
  endTimestamp: z.optional(z.iso.datetime()),
});

export const zAccountSearchAccountsData = z.object({
  body: zSearchAccountRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The search account response.
 */
export const zAccountSearchAccountsResponse = zSearchAccountResponse;

export const zAuthLoginAppData = z.object({
  body: zLoginAppRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAuthLoginAppResponse = zLoginResponse;

export const zAuthLoginKeyData = z.object({
  body: zLoginApiKeyRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAuthLoginKeyResponse = zLoginResponse;

export const zAuthLogoutData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAuthLogoutResponse = zLogoutResponse;

export const zAuthValidateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAuthValidateResponse = zValidateResponse;

export const zContractSearchContractsData = z.object({
  body: zSearchContractRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response containing the search results, including any matching contracts.
 */
export const zContractSearchContractsResponse = zSearchContractResponse;

export const zContractSearchContractByIdData = z.object({
  body: zSearchContractByIdRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response containing the search result, including the matching contract if found.
 */
export const zContractSearchContractByIdResponse = zSearchContractByIdResponse;

export const zContractAvailableContractsData = z.object({
  body: zListAvailableContractRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response containing the list of available contracts.
 */
export const zContractAvailableContractsResponse =
  zListAvailableContractResponse;

export const zHistoryGetBarsData = z.object({
  body: zRetrieveBarRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The response with the retrieved bars.
 */
export const zHistoryGetBarsResponse = zRetrieveBarResponse;

export const zOrderSearchOrdersData = z.object({
  body: zSearchOrderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with search results.
 */
export const zOrderSearchOrdersResponse = zSearchOrderResponse;

export const zOrderSearchOpenOrdersData = z.object({
  body: zSearchOpenOrderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with search results.
 */
export const zOrderSearchOpenOrdersResponse = zSearchOrderResponse;

export const zOrderPlaceOrderData = z.object({
  body: zPlaceOrderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with order placement details.
 */
export const zOrderPlaceOrderResponse = zPlaceOrderResponse;

export const zOrderCancelOrderData = z.object({
  body: zCancelOrderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with order cancellation details.
 */
export const zOrderCancelOrderResponse = zCancelOrderResponse;

export const zOrderModifyOrderData = z.object({
  body: zModifyOrderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with order modification details.
 */
export const zOrderModifyOrderResponse = zModifyOrderResponse;

export const zPositionSearchOpenPositionsData = z.object({
  body: zSearchPositionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with search results.
 */
export const zPositionSearchOpenPositionsResponse = zSearchPositionResponse;

export const zPositionCloseContractPositionData = z.object({
  body: zCloseContractPositionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response indicating the success or failure of the close operation.
 */
export const zPositionCloseContractPositionResponse = zClosePositionResponse;

export const zPositionPartialCloseContractPositionData = z.object({
  body: zPartialCloseContractPositionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response indicating the success or failure of the partial close operation.
 */
export const zPositionPartialCloseContractPositionResponse =
  zPartialClosePositionResponse;

export const zStatusPingData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Returns a "pong" to indicate the API is responsive.
 */
export const zStatusPingResponse = z.string();

export const zTradeSearchHalfTurnTradesData = z.object({
  body: zSearchTradeRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A response with the search results.
 */
export const zTradeSearchHalfTurnTradesResponse = zSearchHalfTradeResponse;
